//! Code formatting utilities for the emitter framework.
//!
//! This module provides two main utilities:
//!
//! - [`CodeBuffer`]: A line-based code buffer with indentation support,
//!   used to accumulate lines of source code before emitting them.
//! - [`CommentWriter`]: Generates source file headers and documentation
//!   comments in various formats (block, line, doc comments).

/// Default indent size in spaces (TypeScript convention: 2 spaces).
pub const INDENT_SIZE: usize = 2;

/// A line-based code buffer with indentation support.
///
/// `CodeBuffer` accumulates lines of source code and tracks the current
/// indentation level. When a line is pushed, the current indentation is
/// prepended automatically.
///
/// # Example
///
/// ```ignore
/// let mut buf = CodeBuffer::new();
/// buf.indent();
/// buf.push_line("if (condition) {");
/// buf.indent();
/// buf.push_line("doSomething();");
/// buf.dedent();
/// buf.push_line("}");
/// ```
#[derive(Debug, Clone)]
pub struct CodeBuffer {
    lines: Vec<String>,
    indent_level: usize,
    indent_str: String,
    indent_size: usize,
}

impl CodeBuffer {
    /// Create a new, empty `CodeBuffer` with indentation level 0
    /// and the default indent size of 2 spaces.
    pub fn new() -> Self {
        Self {
            lines: Vec::new(),
            indent_level: 0,
            indent_str: String::new(),
            indent_size: INDENT_SIZE,
        }
    }

    /// Create a new, empty `CodeBuffer` with a custom indent size.
    ///
    /// Use 2 for TypeScript, 4 for Python/Java.
    pub fn with_indent_size(size: usize) -> Self {
        Self {
            lines: Vec::new(),
            indent_level: 0,
            indent_str: String::new(),
            indent_size: size,
        }
    }

    /// Set the indent size (number of spaces per indent level).
    ///
    /// Rebuilds the current indent string to match the new size.
    pub fn set_indent_size(&mut self, size: usize) {
        self.indent_size = size;
        self.indent_str = " ".repeat(self.indent_level * self.indent_size);
    }

    /// Increase indentation level by 1.
    pub fn indent(&mut self) {
        self.indent_level += 1;
        self.indent_str.push_str(&" ".repeat(self.indent_size));
    }

    /// Decrease indentation level by 1 (minimum 0).
    ///
    /// If the current level is already 0, this is a no-op.
    pub fn dedent(&mut self) {
        if self.indent_level > 0 {
            self.indent_level -= 1;
            let new_len = self.indent_str.len().saturating_sub(self.indent_size);
            self.indent_str.truncate(new_len);
        }
    }

    /// Push a line with the current indentation prepended.
    ///
    /// The line content itself is stored without a trailing newline; the
    /// newline is added when the buffer is materialised via [`into_string`].
    pub fn push_line(&mut self, line: impl AsRef<str>) {
        let mut s = self.indent_str.clone();
        s.push_str(line.as_ref());
        self.lines.push(s);
    }

    /// Push multiple lines, each indented at the current level.
    ///
    /// Equivalent to calling [`push_line`] for each element in the slice.
    pub fn push_lines(&mut self, lines: &[String]) {
        for line in lines {
            self.push_line(line);
        }
    }

    /// Push an empty line (no indentation, just a blank line).
    pub fn push_empty(&mut self) {
        self.lines.push(String::new());
    }

    /// Consume the buffer and return the accumulated output as a `String`.
    ///
    /// Lines are joined with `'\n'` and a trailing newline is appended.
    pub fn into_string(self) -> String {
        if self.lines.is_empty() {
            return String::new();
        }
        self.lines.join("\n") + "\n"
    }

    /// Current indentation level (number of indent steps, each
    /// [`INDENT_SIZE`] spaces wide).
    pub fn indent_level(&self) -> usize {
        self.indent_level
    }

    /// Number of lines in the buffer.
    pub fn len(&self) -> usize {
        self.lines.len()
    }

    /// Whether the buffer is empty (no lines have been pushed).
    pub fn is_empty(&self) -> bool {
        self.lines.is_empty()
    }
}

impl Default for CodeBuffer {
    fn default() -> Self {
        Self::new()
    }
}

/// Generates source file headers and documentation comments.
///
/// `CommentWriter` produces formatted comment strings for generated source
/// files, including file headers, block comments (`/* ... */`), line
/// comments (`// ...`), and doc comments (`/// ...`).
///
/// # Example
///
/// ```ignore
/// let cw = CommentWriter::new();
/// let header = cw.write_header("Dwarf", "0.1.0");
/// let doc = cw.write_doc_comment("This module does something.");
/// ```
pub struct CommentWriter;

impl CommentWriter {
    /// Create a new `CommentWriter`.
    pub fn new() -> Self {
        Self
    }

    /// Generate a "Generated by" file header comment (using `//` style).
    ///
    /// Returns a single-line `//` comment indicating the tool and version
    /// that generated the file.
    pub fn write_header(&self, tool: &str, version: &str) -> String {
        format!(
            "// Generated by {} v{} — edit the .kzd source, not this file",
            tool, version
        )
    }

    /// Generate a "Generated by" file header comment (using `#` style for Python).
    ///
    /// Returns a single-line `#` comment indicating the tool and version
    /// that generated the file.
    pub fn write_py_header(&self, tool: &str, version: &str) -> String {
        format!(
            "# Generated by {} v{} — edit the .kzd source, not this file",
            tool, version
        )
    }

    /// Write a block comment (`/* ... */`).
    ///
    /// For single-line text, produces `/* text */`.
    /// For multi-line text, produces a `/*` line, then each line prefixed
    /// with ` * `, then a ` */` line.
    pub fn write_block_comment(&self, text: &str) -> String {
        if text.is_empty() {
            return "/**/".to_string();
        }
        if !text.contains('\n') {
            return format!("/* {} */", text);
        }
        let mut result = String::from("/*\n");
        for line in text.lines() {
            result.push_str(" * ");
            result.push_str(line);
            result.push('\n');
        }
        result.push_str(" */");
        result
    }

    /// Write a line comment (`// ...`).
    ///
    /// Each line in `text` is prefixed with `// `.
    pub fn write_line_comment(&self, text: &str) -> String {
        if text.is_empty() {
            return "//".to_string();
        }
        format!("// {}", text)
    }

    /// Write a doc comment (`/// ...`).
    ///
    /// Each line in `text` is prefixed with `/// `.
    pub fn write_doc_comment(&self, text: &str) -> String {
        text.lines()
            .map(|line| format!("/// {}", line))
            .collect::<Vec<_>>()
            .join("\n")
    }
}

impl Default for CommentWriter {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ==================================================================
    // CodeBuffer — Creation and empty state
    // ==================================================================

    #[test]
    fn test_new_buffer_empty() {
        let buf = CodeBuffer::new();
        assert_eq!(buf.len(), 0, "new buffer should have len() == 0");
        assert!(buf.is_empty(), "new buffer should be empty");
    }

    #[test]
    fn test_buffer_default_empty() {
        let buf = CodeBuffer::default();
        assert_eq!(buf.len(), 0, "default buffer should have len() == 0");
        assert!(buf.is_empty(), "default buffer should be empty");
    }

    // ==================================================================
    // CodeBuffer — push_line
    // ==================================================================

    #[test]
    fn test_push_single_line() {
        let mut buf = CodeBuffer::new();
        buf.push_line("hello");
        assert_eq!(buf.len(), 1, "buffer should have one line after push");
        assert!(!buf.is_empty(), "buffer should not be empty after push");
    }

    #[test]
    fn test_push_line_with_indent() {
        let mut buf = CodeBuffer::new();
        buf.indent();
        buf.push_line("indented");
        assert_eq!(buf.len(), 1);
        let output = buf.into_string();
        // Indented line should start with INDENT_SIZE spaces
        let prefix = " ".repeat(INDENT_SIZE);
        assert!(
            output.starts_with(&prefix),
            "indented line should start with {INDENT_SIZE} spaces, got: {output:?}"
        );
    }

    #[test]
    fn test_push_multiple_lines() {
        let mut buf = CodeBuffer::new();
        buf.push_line("first");
        buf.push_line("second");
        buf.push_line("third");
        assert_eq!(buf.len(), 3, "buffer should have three lines");
        let output = buf.into_string();
        let lines: Vec<&str> = output.lines().collect();
        assert_eq!(lines.len(), 3, "output should have three lines");
        assert_eq!(lines[0], "first", "first line should be 'first'");
        assert_eq!(lines[1], "second", "second line should be 'second'");
        assert_eq!(lines[2], "third", "third line should be 'third'");
    }

    #[test]
    fn test_push_line_then_into_string() {
        let mut buf = CodeBuffer::new();
        buf.push_line("line1");
        buf.push_line("line2");
        let output = buf.into_string();
        assert!(output.contains("line1"), "output should contain 'line1'");
        assert!(output.contains("line2"), "output should contain 'line2'");
        // into_string should consume the buffer; uncommenting the next line
        // would be a compile error because buf is moved:
        // let _ = buf.len();
    }

    // ==================================================================
    // CodeBuffer — indent / dedent
    // ==================================================================

    #[test]
    fn test_indent_increases_level() {
        let mut buf = CodeBuffer::new();
        assert_eq!(buf.indent_level(), 0, "initial indent level should be 0");
        buf.indent();
        assert_eq!(
            buf.indent_level(),
            1,
            "indent level should be 1 after indent()"
        );
        buf.indent();
        assert_eq!(
            buf.indent_level(),
            2,
            "indent level should be 2 after two indent() calls"
        );
    }

    #[test]
    fn test_dedent_decreases_level() {
        let mut buf = CodeBuffer::new();
        buf.indent();
        buf.indent();
        assert_eq!(buf.indent_level(), 2);
        buf.dedent();
        assert_eq!(buf.indent_level(), 1, "dedent should decrease level by 1");
        buf.dedent();
        assert_eq!(buf.indent_level(), 0, "dedent should return to 0");
    }

    #[test]
    fn test_dedent_below_zero() {
        let mut buf = CodeBuffer::new();
        // Dedenting at level 0 should not panic and stay at 0
        buf.dedent();
        assert_eq!(buf.indent_level(), 0, "dedent at level 0 should stay at 0");
        buf.dedent();
        buf.dedent();
        assert_eq!(
            buf.indent_level(),
            0,
            "repeated dedent at level 0 should stay at 0"
        );
    }

    #[test]
    fn test_indent_dedent_line_content() {
        let mut buf = CodeBuffer::new();
        buf.push_line("top");
        buf.indent();
        buf.push_line("indented");
        buf.dedent();
        buf.push_line("back");
        let output = buf.into_string();
        let lines: Vec<&str> = output.lines().collect();
        assert_eq!(lines.len(), 3);
        assert_eq!(lines[0], "top", "first line should not be indented");
        let indent_str = " ".repeat(INDENT_SIZE);
        assert_eq!(
            lines[1],
            format!("{indent_str}indented"),
            "second line should be indented"
        );
        assert_eq!(lines[2], "back", "third line should not be indented");
    }

    #[test]
    fn test_multiple_indents() {
        let mut buf = CodeBuffer::new();
        for _ in 0..3 {
            buf.indent();
        }
        assert_eq!(buf.indent_level(), 3, "indent level should be 3");
        buf.push_line("deep");
        let output = buf.into_string();
        let prefix = " ".repeat(INDENT_SIZE * 3);
        assert!(
            output.starts_with(&prefix),
            "3 indents should produce {} spaces, got: {output:?}",
            INDENT_SIZE * 3
        );
    }

    #[test]
    fn test_indent_level_starts_at_zero() {
        let buf = CodeBuffer::new();
        assert_eq!(
            buf.indent_level(),
            0,
            "new buffer should have indent_level 0"
        );
    }

    // ==================================================================
    // CodeBuffer — push_lines
    // ==================================================================

    #[test]
    fn test_push_lines_empty() {
        let mut buf = CodeBuffer::new();
        buf.push_lines(&[]);
        assert_eq!(buf.len(), 0, "pushing empty slice should not add any lines");
        assert!(buf.is_empty(), "buffer should remain empty");
    }

    #[test]
    fn test_push_lines_multiple() {
        let mut buf = CodeBuffer::new();
        let lines = vec!["alpha".to_string(), "beta".to_string(), "gamma".to_string()];
        buf.push_lines(&lines);
        assert_eq!(buf.len(), 3, "buffer should have three lines");
        let output = buf.into_string();
        let result_lines: Vec<&str> = output.lines().collect();
        assert_eq!(result_lines[0], "alpha", "first line should be 'alpha'");
        assert_eq!(result_lines[1], "beta", "second line should be 'beta'");
        assert_eq!(result_lines[2], "gamma", "third line should be 'gamma'");
    }

    // ==================================================================
    // CodeBuffer — push_empty
    // ==================================================================

    #[test]
    fn test_push_empty_line() {
        let mut buf = CodeBuffer::new();
        buf.push_line("before");
        buf.push_empty();
        buf.push_line("after");
        assert_eq!(buf.len(), 3, "buffer should have three lines");
        let output = buf.into_string();
        let lines: Vec<&str> = output.lines().collect();
        assert_eq!(lines.len(), 3);
        assert_eq!(lines[0], "before", "first line should be 'before'");
        assert_eq!(lines[1], "", "second line should be empty (blank line)");
        assert_eq!(lines[2], "after", "third line should be 'after'");
    }

    // ==================================================================
    // CodeBuffer — Edge cases
    // ==================================================================

    #[test]
    fn test_buffer_with_empty_string() {
        let mut buf = CodeBuffer::new();
        buf.push_line("");
        assert_eq!(buf.len(), 1, "pushing an empty string should add one line");
        let output = buf.into_string();
        // An empty line (just the trailing newline content)
        assert_eq!(output, "\n", "empty push should produce just a newline");
    }

    // ==================================================================
    // CodeBuffer — indent_size (configurable indentation)
    // ==================================================================

    #[test]
    fn test_with_indent_size_4() {
        let mut buf = CodeBuffer::with_indent_size(4);
        assert_eq!(
            buf.indent_level(),
            0,
            "new with_indent_size(4) should have indent_level 0"
        );
        buf.indent();
        assert_eq!(buf.indent_level(), 1);
        buf.push_line("four spaces");
        let output = buf.into_string();
        assert!(
            output.starts_with("    "),
            "4-space indent should produce 4 spaces, got: {output:?}"
        );
    }

    #[test]
    fn test_set_indent_size() {
        let mut buf = CodeBuffer::new();
        buf.set_indent_size(4);
        buf.indent();
        buf.push_line("now four");
        let output = buf.into_string();
        assert!(
            output.starts_with("    "),
            "after set_indent_size(4), indent should be 4 spaces, got: {output:?}"
        );
    }

    #[test]
    fn test_set_indent_size_rebuilds_existing() {
        let mut buf = CodeBuffer::new();
        buf.indent();
        buf.indent();
        // 2 levels at default 2 spaces = 4 spaces
        assert_eq!(buf.indent_level(), 2);
        // Switch to 4 spaces
        buf.set_indent_size(4);
        buf.push_line("after resize");
        let output = buf.into_string();
        // 2 levels at 4 spaces = 8 spaces
        let prefix = " ".repeat(8);
        assert!(
            output.starts_with(&prefix),
            "after set_indent_size(4) at level 2, should produce 8 spaces, got: {output:?}"
        );
    }

    #[test]
    fn test_indent_custom_size() {
        let mut buf = CodeBuffer::with_indent_size(8);
        buf.indent();
        assert_eq!(buf.indent_level(), 1);
        buf.push_line("wide");
        let output = buf.into_string();
        assert!(
            output.starts_with("        "),
            "8-space indent should produce 8 spaces, got: {output:?}"
        );
    }

    #[test]
    fn test_dedent_custom_size() {
        let mut buf = CodeBuffer::with_indent_size(4);
        buf.indent();
        buf.indent();
        assert_eq!(buf.indent_level(), 2);
        buf.dedent();
        assert_eq!(buf.indent_level(), 1);
        buf.push_line("level1");
        let output = buf.into_string();
        assert!(
            output.starts_with("    "),
            "after dedent from level 2 to 1 with 4-space indent, should produce 4 spaces, got: {output:?}"
        );
    }

    // ==================================================================
    // CodeBuffer — clone independence
    // ==================================================================

    #[test]
    fn test_clone_independence() {
        let mut buf = CodeBuffer::new();
        buf.push_line("original");
        let mut cloned = buf.clone();
        cloned.push_line("cloned addition");

        // Original should not have the cloned addition
        assert_eq!(buf.len(), 1, "original should still have 1 line");
        assert!(
            buf.into_string().contains("original"),
            "original should contain 'original'"
        );

        // Clone should have both lines
        assert_eq!(cloned.len(), 2, "clone should have 2 lines");
        assert!(
            cloned.into_string().contains("cloned addition"),
            "clone should contain 'cloned addition'"
        );
    }

    // ==================================================================
    // CommentWriter — write_header
    // ==================================================================

    #[test]
    fn test_write_header_format() {
        let cw = CommentWriter::new();
        let header = cw.write_header("Dwarf", "0.1.0");
        assert!(
            header.contains("Generated by Dwarf"),
            "header should contain 'Generated by Dwarf'"
        );
        assert!(
            header.contains("0.1.0"),
            "header should contain version string"
        );
        assert!(
            header.contains("edit the .kzd source, not this file"),
            "header should contain 'edit the .kzd source, not this file'"
        );
        assert!(header.starts_with("//"), "header should start with //");
    }

    #[test]
    fn test_write_header_custom_tool() {
        let cw = CommentWriter::new();
        let header = cw.write_header("MyTool", "2.0.0");
        assert!(
            header.contains("Generated by MyTool"),
            "header should contain custom tool name"
        );
        assert!(
            header.contains("2.0.0"),
            "header should contain custom version"
        );
    }

    #[test]
    fn test_write_header_empty_version() {
        let cw = CommentWriter::new();
        let header = cw.write_header("Dwarf", "");
        assert!(
            header.contains("Generated by Dwarf"),
            "header should contain tool name even with empty version"
        );
    }

    #[test]
    fn test_write_py_header_format() {
        let cw = CommentWriter::new();
        let header = cw.write_py_header("Dwarf", "0.1.0");
        assert!(
            header.contains("Generated by Dwarf"),
            "py header should contain 'Generated by Dwarf'"
        );
        assert!(
            header.contains("0.1.0"),
            "py header should contain version string"
        );
        assert!(
            header.contains("edit the .kzd source, not this file"),
            "py header should contain 'edit the .kzd source, not this file'"
        );
        assert!(header.starts_with("#"), "py header should start with #");
    }

    #[test]
    fn test_write_py_header_custom_tool() {
        let cw = CommentWriter::new();
        let header = cw.write_py_header("PyTool", "3.0.0");
        assert!(
            header.contains("Generated by PyTool"),
            "py header should contain custom tool name"
        );
        assert!(
            header.starts_with("#"),
            "py header should start with # for Python"
        );
    }

    // ==================================================================
    // CommentWriter — write_block_comment
    // ==================================================================

    #[test]
    fn test_block_comment_single_line() {
        let cw = CommentWriter::new();
        let comment = cw.write_block_comment("hello");
        assert_eq!(
            comment, "/* hello */",
            "single-line block comment should be '/* hello */'"
        );
    }

    #[test]
    fn test_block_comment_multiline() {
        let cw = CommentWriter::new();
        let comment = cw.write_block_comment("line1\nline2\nline3");
        // Multi-line block comment format:
        // /*
        //  * line1
        //  * line2
        //  * line3
        //  */
        assert!(
            comment.starts_with("/*"),
            "multiline block comment should start with '/*'"
        );
        assert!(
            comment.contains("line1"),
            "multiline block comment should contain its text"
        );
        assert!(
            comment.contains("line2"),
            "multiline block comment should contain its text"
        );
        assert!(
            comment.contains("line3"),
            "multiline block comment should contain its text"
        );
        assert!(
            comment.ends_with("*/"),
            "multiline block comment should end with '*/'"
        );
    }

    #[test]
    fn test_block_comment_empty() {
        let cw = CommentWriter::new();
        let comment = cw.write_block_comment("");
        assert!(
            comment.starts_with("/*"),
            "empty block comment should start with '/*'"
        );
        assert!(
            comment.ends_with("*/"),
            "empty block comment should end with '*/'"
        );
    }

    // ==================================================================
    // CommentWriter — write_line_comment
    // ==================================================================

    #[test]
    fn test_line_comment_format() {
        let cw = CommentWriter::new();
        let comment = cw.write_line_comment("hello");
        assert_eq!(comment, "// hello", "line comment should be '// hello'");
    }

    #[test]
    fn test_line_comment_empty() {
        let cw = CommentWriter::new();
        let comment = cw.write_line_comment("");
        assert_eq!(comment, "//", "line comment with empty text should be '//'");
    }

    // ==================================================================
    // CommentWriter — write_doc_comment
    // ==================================================================

    #[test]
    fn test_doc_comment_format() {
        let cw = CommentWriter::new();
        let comment = cw.write_doc_comment("hello");
        assert_eq!(comment, "/// hello", "doc comment should be '/// hello'");
    }

    #[test]
    fn test_doc_comment_multiline() {
        let cw = CommentWriter::new();
        let comment = cw.write_doc_comment("line1\nline2");
        let lines: Vec<&str> = comment.lines().collect();
        assert_eq!(lines.len(), 2, "multiline doc comment should have 2 lines");
        assert_eq!(lines[0], "/// line1", "first line should be '/// line1'");
        assert_eq!(lines[1], "/// line2", "second line should be '/// line2'");
    }
}
