//! A TypeScript backend that produces real TypeScript code from LIR.
//!
//! This backend implements [`EmitterBackend`] with `Output = String` and
//! produces TypeScript source code suitable for further compilation or
//! direct execution in a TypeScript runtime.
//!
//! # Status
//!
//! This backend is a work in progress. Only the following methods have real
//! implementations:
//!
//! - `emit_literal` — produces TypeScript literal syntax
//! - `emit_binary_op` — produces TypeScript binary operators (with spaces)
//! - `emit_unary_op` — produces TypeScript unary operators
//! - `emit_target_hint` — produces target-hint strings
//! - `emit_effect` — produces effect-annotation strings
//! - `emit_type` — delegates to [`TypeScriptMapper`]
//! - `emit_pat` — produces TypeScript pattern syntax
//!
//! All [`EmitterBackend`] methods now have real implementations.

use dwarf_lir::{
    Effect, LirBinaryOp, LirDecl, LirExpr, LirLiteral, LirParam, LirPat, LirStmt, LirUnaryOp,
    TargetHint,
};
use dwarf_syntax::diagnostic::byte_to_line_col;
use dwarf_syntax::hir::Type;
use dwarf_syntax::span::Span;

use crate::backend::EmitterBackend;
use crate::error::EmitterError;
use crate::format::CodeBuffer;
use crate::sourcemap::{SourceMapBuilder, SourceMapOutput};
use crate::ts::imports::ImportManager;
use crate::ts::mapper::TypeScriptMapper;
use crate::types::TypeMapper;

/// A backend that emits TypeScript code from LIR declarations.
///
/// Each method accepts a reference to a LIR construct and produces a
/// TypeScript string representation. The `Output` type is `String`,
/// containing the complete emitted module.
pub struct TypeScriptBackend {
    buffer: CodeBuffer,
    type_mapper: TypeScriptMapper,
    imports: ImportManager,
    version: String,
}

impl TypeScriptBackend {
    /// Create a new `TypeScriptBackend` with an empty buffer, a fresh
    /// [`TypeScriptMapper`], an empty [`ImportManager`], and the given
    /// version string for the generated-file header.
    pub fn new(version: &str) -> Self {
        Self {
            buffer: CodeBuffer::new(),
            type_mapper: TypeScriptMapper,
            imports: ImportManager::new(),
            version: version.to_string(),
        }
    }

    /// Return a reference to the internal [`CodeBuffer`].
    pub fn buffer(&self) -> &CodeBuffer {
        &self.buffer
    }

    /// Return a mutable reference to the internal [`CodeBuffer`].
    pub fn buffer_mut(&mut self) -> &mut CodeBuffer {
        &mut self.buffer
    }

    /// Consume the backend and return the accumulated output as a `String`.
    pub fn into_output(self) -> String {
        self.buffer.into_string()
    }

    /// Register an import from a module (without alias).
    ///
    /// This adds `import { name } from 'module'` to the output when
    /// [`emit_module`](EmitterBackend::emit_module) is called.
    pub fn add_import(&mut self, module: &str, name: &str) {
        self.imports.add_import(module, name, None);
    }

    /// Emit declarations with source map generation.
    ///
    /// `source_name` is the original source filename.
    /// `source_content` is the original source content.
    pub fn emit_module_with_sourcemap(
        &mut self,
        decls: &[LirDecl],
        source_name: &str,
        source_content: &str,
    ) -> Result<SourceMapOutput, EmitterError> {
        let mut builder = SourceMapBuilder::new(source_name, source_content);

        // For each declaration, record a mapping from the generated position
        // back to the source position.
        for (i, decl) in decls.iter().enumerate() {
            // Get the source position from the span
            let src_pos = decl_span(decl).map(|span| span_to_line_col(source_content, &span));

            if let Some((src_line, src_col)) = src_pos {
                // The generated line is approximately:
                // Header line (1) + blank line (1) + decl index offset
                // This is approximate — in a full implementation we'd track
                // exact positions from the CodeBuffer
                let gen_line = i as u32 + 2; // After the "Generated by" header
                builder.add_mapping(gen_line, 0, src_line, src_col, None);
            }
        }

        let output = self.emit_module(decls)?;

        Ok(SourceMapOutput {
            output,
            source_map: Some(builder.into_json()),
        })
    }
}

impl Default for TypeScriptBackend {
    fn default() -> Self {
        Self::new("0.1.0")
    }
}

impl EmitterBackend for TypeScriptBackend {
    type Output = String;

    fn emit_module_with_source_map(
        &mut self,
        decls: &[LirDecl],
        source_name: &str,
        source_content: &str,
    ) -> Result<(Self::Output, Option<serde_json::Value>), EmitterError> {
        let result = self.emit_module_with_sourcemap(decls, source_name, source_content)?;
        Ok((result.output, result.source_map))
    }

    fn emit_module(&mut self, decls: &[LirDecl]) -> Result<String, EmitterError> {
        if decls.is_empty() && self.imports.is_empty() {
            return Ok(String::new());
        }
        let mut buf = CodeBuffer::new();

        // Generated file header
        buf.push_line(format!(
            "// Generated by Dwarf v{} -- edit source, not this file",
            self.version
        ));
        buf.push_empty();

        // Emit imports at the top of the module, if any
        if !self.imports.is_empty() {
            for import_line in self.imports.emit_imports() {
                buf.push_line(&import_line);
            }
            buf.push_empty();
        }

        // Emit declarations
        for (i, decl) in decls.iter().enumerate() {
            if i > 0 {
                buf.push_empty();
            }
            let decl_str = self.emit_decl(decl)?;
            // Push each line of the decl with proper indentation
            for line in decl_str.lines() {
                buf.push_line(line);
            }
        }
        Ok(buf.into_string().trim_end().to_string())
    }

    fn emit_decl(&mut self, decl: &LirDecl) -> Result<String, EmitterError> {
        match decl {
            LirDecl::Function {
                name,
                params,
                return_type,
                body,
                effect,
                hint,
                is_pub,
                ..
            } => {
                // JSX (React component) functions use a different emission format
                if *hint == TargetHint::ReactComponent {
                    return self.emit_jsx_function(name, params, body, *is_pub);
                }
                let export_prefix = if *is_pub { "export " } else { "" };
                let async_prefix = if *hint == TargetHint::Async || *effect == Effect::Async {
                    "async "
                } else {
                    ""
                };
                let params_str: Vec<String> = params
                    .iter()
                    .map(|p| match &p.type_ {
                        Some(ty) => format!("{}: {}", p.name, self.type_mapper.map_type(ty)),
                        None => p.name.clone(),
                    })
                    .collect();
                let ret_str = match return_type {
                    Some(ty) => format!(": {}", self.type_mapper.map_type(ty)),
                    None => String::new(),
                };
                let header = format!(
                    "{}{}function {}({}){}",
                    export_prefix,
                    async_prefix,
                    name,
                    params_str.join(", "),
                    ret_str
                );

                // If the body is a Block, use proper multi-line formatting
                match body {
                    LirExpr::Block { stmts, .. } => {
                        let mut buf = CodeBuffer::new();
                        buf.push_line(format!("{} {{", header));
                        buf.indent();
                        for (i, stmt) in stmts.iter().enumerate() {
                            let is_last = i == stmts.len() - 1;
                            match stmt {
                                LirStmt::Let { pat, value } => {
                                    let val_str = self.emit_expr(value)?;
                                    let pat_str = self.emit_pat_inline(pat);
                                    buf.push_line(format!("let {} = {};", pat_str, val_str));
                                }
                                LirStmt::Expr(expr) => {
                                    let expr_str = self.emit_expr(expr)?;
                                    if is_last {
                                        buf.push_line(format!("return {};", expr_str));
                                    } else {
                                        buf.push_line(format!("{};", expr_str));
                                    }
                                }
                            }
                        }
                        buf.dedent();
                        buf.push_line("}");
                        Ok(buf.into_string().trim_end().to_string())
                    }
                    other => {
                        let body_str = self.emit_expr(other)?;
                        Ok(format!("{} {{ return {}; }}", header, body_str))
                    }
                }
            }
            LirDecl::RecordDef {
                name,
                fields,
                is_pub,
                ..
            } => {
                let export_prefix = if *is_pub { "export " } else { "" };
                let fields_str: Vec<String> = fields
                    .iter()
                    .map(|f| format!("{}: {};", f.name, self.type_mapper.map_type(&f.type_)))
                    .collect();
                Ok(format!(
                    "{}interface {} {{ {} }}",
                    export_prefix,
                    name,
                    fields_str.join(" ")
                ))
            }
            LirDecl::UnionDef {
                name,
                variants,
                is_pub,
                ..
            } => {
                let export_prefix = if *is_pub { "export " } else { "" };
                let variants_str: Vec<String> = variants
                    .iter()
                    .map(|v| match &v.arg {
                        Some(_ty) => v.name.clone(),
                        None => v.name.clone(),
                    })
                    .collect();
                Ok(format!(
                    "{}type {} = {};",
                    export_prefix,
                    name,
                    variants_str.join(" | ")
                ))
            }
        }
    }

    fn emit_expr(&mut self, expr: &LirExpr) -> Result<String, EmitterError> {
        match expr {
            LirExpr::Literal { value, .. } => self.emit_literal(value),
            LirExpr::Variable { name, .. } => Ok(name.clone()),
            LirExpr::Call {
                func, args, hint, ..
            } => {
                // Check for assert/assert_eq → Jest expect compilation
                if let LirExpr::Variable { name, .. } = func.as_ref() {
                    match name.as_str() {
                        "assert" if args.len() == 1 => {
                            let arg = self.emit_expr(&args[0])?;
                            return Ok(format!("expect({}).toBe(true)", arg));
                        }
                        "assert_eq" if args.len() == 2 => {
                            let a = self.emit_expr(&args[0])?;
                            let b = self.emit_expr(&args[1])?;
                            return Ok(format!("expect({}).toBe({})", a, b));
                        }
                        _ => {} // fall through to regular call
                    }
                } else if let LirExpr::Member { obj, field, .. } = func.as_ref() {
                    if let LirExpr::Variable { name: obj_name, .. } = obj.as_ref() {
                        if obj_name == "assert" {
                            match (field.as_str(), args.len()) {
                                ("equal", 2) => {
                                    let a = self.emit_expr(&args[0])?;
                                    let b = self.emit_expr(&args[1])?;
                                    return Ok(format!("expect({}).toBe({})", a, b));
                                }
                                ("ok", 1) => {
                                    let val = self.emit_expr(&args[0])?;
                                    return Ok(format!("expect({}).toBeTruthy()", val));
                                }
                                ("error", 1) => {
                                    let fn_expr = self.emit_expr(&args[0])?;
                                    return Ok(format!("expect({}).toThrow()", fn_expr));
                                }
                                ("struct", 2) => {
                                    let a = self.emit_expr(&args[0])?;
                                    let b = self.emit_expr(&args[1])?;
                                    return Ok(format!("expect({}).toEqual({})", a, b));
                                }
                                _ => {} // fall through to regular call
                            }
                        }
                    }
                }
                let func_str = self.emit_expr(func)?;
                let args_str: Vec<String> = args
                    .iter()
                    .map(|a| self.emit_expr(a))
                    .collect::<Result<Vec<_>, _>>()?;
                let call = format!("{}({})", func_str, args_str.join(", "));
                if *hint == TargetHint::Async {
                    Ok(format!("await {}", call))
                } else {
                    Ok(call)
                }
            }
            LirExpr::Member {
                obj, field, hint, ..
            } => {
                let obj_str = self.emit_expr(obj)?;
                let op = if *hint == TargetHint::Optional {
                    "?."
                } else {
                    "."
                };
                Ok(format!("{}{}{}", obj_str, op, field))
            }
            LirExpr::If {
                cond, then, else_, ..
            } => {
                let cond_str = self.emit_expr(cond)?;
                let then_str = self.emit_expr(then)?;
                match else_ {
                    Some(else_expr) => {
                        let else_str = self.emit_expr(else_expr)?;
                        Ok(format!("{} ? {} : {}", cond_str, then_str, else_str))
                    }
                    None => Ok(then_str),
                }
            }
            LirExpr::Match { expr, arms, .. } => {
                let expr_str = self.emit_expr(expr)?;
                if arms.is_empty() {
                    return Ok(String::new());
                }
                let mut chain = String::new();
                for (i, arm) in arms.iter().enumerate() {
                    let body_str = self.emit_expr(&arm.body)?;
                    let is_last = i == arms.len() - 1;
                    let is_wildcard_default = is_last && matches!(arm.pattern, LirPat::Wildcard);

                    if is_wildcard_default {
                        if chain.is_empty() {
                            chain = body_str;
                        } else {
                            chain = format!("{} : {}", chain, body_str);
                        }
                    } else {
                        let pat_str = match &arm.pattern {
                            LirPat::Literal(lit) => self.emit_literal(lit)?,
                            LirPat::Wildcard => "_".to_string(),
                            LirPat::Variable(name) => name.clone(),
                            LirPat::Variant { name, .. } => format!("\"{}\"", name),
                            LirPat::Record { .. } => "_".to_string(),
                        };
                        let condition = format!("{} === {}", expr_str, pat_str);
                        if chain.is_empty() {
                            chain = format!("{} ? {}", condition, body_str);
                        } else {
                            chain = format!("{} : {} ? {}", chain, condition, body_str);
                        }
                    }
                }
                Ok(chain)
            }
            LirExpr::Block { stmts, .. } => self.emit_block_body(stmts),
            LirExpr::Assign { target, value, .. } => {
                let target_str = self.emit_expr(target)?;
                let value_str = self.emit_expr(value)?;
                Ok(format!("{} = {}", target_str, value_str))
            }
            LirExpr::Lambda { params, body, .. } => {
                let params_str: Vec<String> = params
                    .iter()
                    .map(|p| match &p.type_ {
                        Some(ty) => format!("{}: {}", p.name, self.type_mapper.map_type(ty)),
                        None => p.name.clone(),
                    })
                    .collect();
                let body_str = self.emit_expr(body)?;
                Ok(format!("({}) => {}", params_str.join(", "), body_str))
            }
            LirExpr::Record { fields, .. } => {
                let fields_str: Vec<String> = fields
                    .iter()
                    .map(|(name, expr)| {
                        let val = self.emit_expr(expr)?;
                        Ok(format!("{}: {}", name, val))
                    })
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(format!("{{ {} }}", fields_str.join(", ")))
            }
            LirExpr::Variant { name, arg, .. } => match arg {
                Some(expr) => {
                    let val = self.emit_expr(expr)?;
                    Ok(format!("{{ tag: \"{}\", value: {} }}", name, val))
                }
                None => Ok(format!("\"{}\"", name)),
            },
            LirExpr::Array { items, .. } => {
                let items_str: Vec<String> = items
                    .iter()
                    .map(|i| self.emit_expr(i))
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(format!("[{}]", items_str.join(", ")))
            }
            LirExpr::Binary { op, lhs, rhs, .. } => {
                let lhs_str = self.emit_expr(lhs)?;
                let rhs_str = self.emit_expr(rhs)?;
                let op_str = self.emit_binary_op(op)?;
                Ok(format!("{}{}{}", lhs_str, op_str, rhs_str))
            }
            LirExpr::Unary { op, expr, .. } => {
                let expr_str = self.emit_expr(expr)?;
                let op_str = self.emit_unary_op(op)?;
                Ok(format!("{}{}", op_str, expr_str))
            }
            LirExpr::Wildcard { .. } => Ok("_".to_string()),
            LirExpr::ForAll {
                type_,
                binding,
                property,
                ..
            } => {
                let ty_str = self.emit_type(type_)?;
                let binding_str = self.emit_pat(binding)?;
                let property_str = self.emit_expr(property)?;
                Ok(format!(
                    "/* forAll<{ty_str}>({binding_str} => {property_str}) */"
                ))
            }
        }
    }

    fn emit_pat(&mut self, pat: &LirPat) -> Result<String, EmitterError> {
        match pat {
            LirPat::Wildcard => Ok("_".to_string()),
            LirPat::Literal(lit) => self.emit_literal(lit),
            LirPat::Variable(name) => Ok(name.clone()),
            LirPat::Variant { name, arg } => match arg {
                Some(a) => {
                    let inner = self.emit_pat(a)?;
                    Ok(format!("{}: {}", name, inner))
                }
                None => Ok(name.clone()),
            },
            LirPat::Record { fields, rest } => {
                let fields_str: Vec<String> = fields
                    .iter()
                    .map(|(name, pat)| {
                        let p = self.emit_pat(pat)?;
                        Ok(format!("{}: {}", name, p))
                    })
                    .collect::<Result<Vec<_>, EmitterError>>()?;
                let rest_str = if *rest { ", ..." } else { "" };
                Ok(format!("{{ {}{} }}", fields_str.join(", "), rest_str))
            }
        }
    }

    fn emit_type(&mut self, ty: &Type) -> Result<String, EmitterError> {
        Ok(self.type_mapper.map_type(ty))
    }

    fn emit_literal(&mut self, lit: &LirLiteral) -> Result<String, EmitterError> {
        match lit {
            LirLiteral::Int(v) => Ok(format!("{v}")),
            LirLiteral::Float(v) => Ok(format!("{v}")),
            LirLiteral::Str(v) => Ok(format!("\"{v}\"")),
            LirLiteral::Bool(v) => Ok(format!("{v}")),
            LirLiteral::Null => Ok("null".into()),
        }
    }

    fn emit_binary_op(&mut self, op: &LirBinaryOp) -> Result<String, EmitterError> {
        match op {
            LirBinaryOp::Add => Ok(" + ".into()),
            LirBinaryOp::Sub => Ok(" - ".into()),
            LirBinaryOp::Mul => Ok(" * ".into()),
            LirBinaryOp::Div => Ok(" / ".into()),
            LirBinaryOp::Eq => Ok(" === ".into()),
            LirBinaryOp::Ne => Ok(" !== ".into()),
            LirBinaryOp::Lt => Ok(" < ".into()),
            LirBinaryOp::Gt => Ok(" > ".into()),
            LirBinaryOp::Le => Ok(" <= ".into()),
            LirBinaryOp::Ge => Ok(" >= ".into()),
            LirBinaryOp::And => Ok(" && ".into()),
            LirBinaryOp::Or => Ok(" || ".into()),
        }
    }

    fn emit_unary_op(&mut self, op: &LirUnaryOp) -> Result<String, EmitterError> {
        match op {
            LirUnaryOp::Neg => Ok("-".into()),
            LirUnaryOp::Not => Ok("!".into()),
        }
    }

    fn emit_target_hint(&mut self, hint: &TargetHint) -> Result<String, EmitterError> {
        match hint {
            TargetHint::None => Ok(String::new()),
            TargetHint::Async => Ok("async ".into()),
            TargetHint::Optional => Ok("?".into()),
            TargetHint::Result => Ok(String::new()),
            TargetHint::ReactComponent => Ok(String::new()),
        }
    }

    fn emit_effect(&mut self, effect: &Effect) -> Result<String, EmitterError> {
        match effect {
            Effect::Pure => Ok(String::new()),
            Effect::Async => Ok("await ".into()),
            Effect::Impure => Ok(String::new()),
        }
    }
}

// ------------------------------------------------------------------
// Internal helpers on TypeScriptBackend
// ------------------------------------------------------------------

impl TypeScriptBackend {
    /// Emit a block body (stmts) as a single-line `{ ... }` string.
    ///
    /// For Let statements we use `emit_pat_inline` which produces a slightly
    /// different format than the trait `emit_pat` method — it uses `()` for
    /// variant args and `..` for record rest, matching TypeScript destructuring
    /// conventions.
    fn emit_block_body(&mut self, stmts: &[LirStmt]) -> Result<String, EmitterError> {
        if stmts.is_empty() {
            return Ok("{}".to_string());
        }
        let mut parts: Vec<String> = Vec::new();
        for (i, stmt) in stmts.iter().enumerate() {
            let is_last = i == stmts.len() - 1;
            match stmt {
                LirStmt::Let { pat, value } => {
                    let val_str = self.emit_expr(value)?;
                    let pat_str = self.emit_pat_inline(pat);
                    parts.push(format!("let {} = {}", pat_str, val_str));
                }
                LirStmt::Expr(expr) => {
                    let expr_str = self.emit_expr(expr)?;
                    if is_last {
                        parts.push(format!("return {}", expr_str));
                    } else {
                        parts.push(expr_str);
                    }
                }
            }
        }
        Ok(format!("{{ {}; }}", parts.join("; ")))
    }

    /// Inline pattern emission helper for `let` statement destructuring.
    ///
    /// This produces a slightly different format than the trait `emit_pat`
    /// method: it uses `Variant(inner)` syntax (matching TypeScript
    /// destructuring) instead of `Variant: inner`, and `..` for record rest
    /// instead of `...`.
    fn emit_pat_inline(&mut self, pat: &LirPat) -> String {
        match pat {
            LirPat::Wildcard => "_".to_string(),
            LirPat::Literal(lit) => self.emit_literal(lit).unwrap_or_else(|_| "_".to_string()),
            LirPat::Variable(name) => name.clone(),
            LirPat::Variant { name, arg } => match arg {
                Some(arg_pat) => format!("{}({})", name, self.emit_pat_inline(arg_pat)),
                None => name.clone(),
            },
            LirPat::Record { fields, rest } => {
                let fields_str: Vec<String> = fields
                    .iter()
                    .map(|(fname, pat)| format!("{}: {}", fname, self.emit_pat_inline(pat)))
                    .collect();
                let mut result = format!("{{ {} ", fields_str.join(", "));
                if *rest {
                    result.push_str(", ..");
                }
                result.push('}');
                result
            }
        }
    }

    /// Emit a function as a React component using JSX syntax.
    ///
    /// Produces output of the form:
    ///
    /// ```typescript
    /// export const Component: React.FC<ComponentProps> = (props) => {
    ///   return (<div>...</div>);
    /// };
    /// ```
    ///
    /// The props type name is derived from the function name by appending `Props`
    /// (e.g. `Button` → `ButtonProps`).
    fn emit_jsx_function(
        &mut self,
        name: &str,
        params: &[LirParam],
        body: &LirExpr,
        is_pub: bool,
    ) -> Result<String, EmitterError> {
        let export = if is_pub { "export " } else { "" };
        let props_type = format!("{}Props", crate::naming::to_pascal_case(name));

        let params_str: Vec<String> = params
            .iter()
            .map(|p| {
                let ty = match &p.type_ {
                    Some(t) => format!(": {}", self.type_mapper.map_type(t)),
                    None => String::new(),
                };
                format!("{}{}", p.name, ty)
            })
            .collect();
        let params_jsx = params_str.join(", ");

        match body {
            LirExpr::Block { stmts, .. } => {
                let mut buf = CodeBuffer::new();
                buf.push_line(format!(
                    "{}const {}: React.FC<{}> = ({}) => {{",
                    export, name, props_type, params_jsx
                ));
                buf.indent();
                for (i, stmt) in stmts.iter().enumerate() {
                    let is_last = i == stmts.len() - 1;
                    match stmt {
                        LirStmt::Let { pat, value } => {
                            let val_str = self.emit_expr(value)?;
                            let pat_str = self.emit_pat_inline(pat);
                            buf.push_line(format!("let {} = {};", pat_str, val_str));
                        }
                        LirStmt::Expr(expr) => {
                            let expr_str = self.emit_expr(expr)?;
                            if is_last {
                                buf.push_line(format!("return ({});", expr_str));
                            } else {
                                buf.push_line(format!("{};", expr_str));
                            }
                        }
                    }
                }
                buf.dedent();
                buf.push_line("};");
                Ok(buf.into_string().trim_end().to_string())
            }
            other => {
                let body_str = self.emit_expr(other)?;
                Ok(format!(
                    "{}const {}: React.FC<{}> = ({}) => {{\n  return ({});\n}};",
                    export, name, props_type, params_jsx, body_str
                ))
            }
        }
    }
}

// ------------------------------------------------------------------
// Free helper functions for source map support
// ------------------------------------------------------------------

/// Extract a source [`Span`] from a LIR declaration, if available.
fn decl_span(decl: &LirDecl) -> Option<Span> {
    match decl {
        LirDecl::Function { span, .. }
        | LirDecl::RecordDef { span, .. }
        | LirDecl::UnionDef { span, .. } => Some(*span),
    }
}

/// Convert a byte-offset [`Span`] to 0-based (line, column) using the
/// source content. Returns `(0, 0)` if the byte offset is out of bounds.
fn span_to_line_col(source: &str, span: &Span) -> (u32, u32) {
    if let Some((line, col)) = byte_to_line_col(source, span.start) {
        // byte_to_line_col returns 1-based line/col; source maps use 0-based
        (line as u32 - 1, col as u32 - 1)
    } else {
        (0, 0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use dwarf_lir::{
        Effect, LirArm, LirBinaryOp, LirField, LirLiteral, LirParam, LirUnaryOp, LirVariant,
        TargetHint,
    };
    use dwarf_syntax::hir::Type;
    use dwarf_syntax::span::Span;

    // ==================================================================
    // Helpers
    // ==================================================================

    fn s() -> Span {
        Span::new(0, 0, 0)
    }

    fn hint_none() -> TargetHint {
        TargetHint::None
    }

    // ==================================================================
    // Creation tests
    // ==================================================================

    #[test]
    fn test_ts_backend_new() {
        let backend = TypeScriptBackend::new("0.1.0");
        assert!(
            backend.buffer.is_empty(),
            "new backend should have empty buffer"
        );
    }

    #[test]
    fn test_ts_backend_default() {
        let backend = TypeScriptBackend::default();
        assert!(
            backend.buffer.is_empty(),
            "default backend should have empty buffer"
        );
    }

    // ==================================================================
    // Literal emission — real implementations
    // ==================================================================

    #[test]
    fn test_emit_literal_int() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_literal(&LirLiteral::Int(42)).unwrap(), "42");
    }

    #[test]
    fn test_emit_literal_float() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(
            backend.emit_literal(&LirLiteral::Float(3.5)).unwrap(),
            "3.5"
        );
    }

    #[test]
    fn test_emit_literal_str() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(
            backend
                .emit_literal(&LirLiteral::Str("hello".into()))
                .unwrap(),
            "\"hello\""
        );
    }

    #[test]
    fn test_emit_literal_bool_true() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(
            backend.emit_literal(&LirLiteral::Bool(true)).unwrap(),
            "true"
        );
    }

    #[test]
    fn test_emit_literal_bool_false() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(
            backend.emit_literal(&LirLiteral::Bool(false)).unwrap(),
            "false"
        );
    }

    #[test]
    fn test_emit_literal_null() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_literal(&LirLiteral::Null).unwrap(), "null");
    }

    // ==================================================================
    // Binary operator emission — real implementations
    // ==================================================================

    #[test]
    fn test_emit_binary_op_add() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_binary_op(&LirBinaryOp::Add).unwrap(), " + ");
    }

    #[test]
    fn test_emit_binary_op_sub() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_binary_op(&LirBinaryOp::Sub).unwrap(), " - ");
    }

    #[test]
    fn test_emit_binary_op_mul() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_binary_op(&LirBinaryOp::Mul).unwrap(), " * ");
    }

    #[test]
    fn test_emit_binary_op_eq() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_binary_op(&LirBinaryOp::Eq).unwrap(), " === ");
    }

    #[test]
    fn test_emit_binary_op_ne() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_binary_op(&LirBinaryOp::Ne).unwrap(), " !== ");
    }

    #[test]
    fn test_emit_binary_op_and() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_binary_op(&LirBinaryOp::And).unwrap(), " && ");
    }

    #[test]
    fn test_emit_binary_op_or() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_binary_op(&LirBinaryOp::Or).unwrap(), " || ");
    }

    // ==================================================================
    // Unary operator emission — real implementations
    // ==================================================================

    #[test]
    fn test_emit_unary_op_neg() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_unary_op(&LirUnaryOp::Neg).unwrap(), "-");
    }

    #[test]
    fn test_emit_unary_op_not() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_unary_op(&LirUnaryOp::Not).unwrap(), "!");
    }

    // ==================================================================
    // Target hint emission — real implementations
    // ==================================================================

    #[test]
    fn test_emit_target_hint_none() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_target_hint(&TargetHint::None).unwrap(), "");
    }

    #[test]
    fn test_emit_target_hint_async() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(
            backend.emit_target_hint(&TargetHint::Async).unwrap(),
            "async "
        );
    }

    #[test]
    fn test_emit_target_hint_optional() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(
            backend.emit_target_hint(&TargetHint::Optional).unwrap(),
            "?"
        );
    }

    #[test]
    fn test_emit_target_hint_result() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_target_hint(&TargetHint::Result).unwrap(), "");
    }

    #[test]
    fn test_emit_target_hint_react_component() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(
            backend
                .emit_target_hint(&TargetHint::ReactComponent)
                .unwrap(),
            ""
        );
    }

    // ==================================================================
    // Effect emission — real implementations
    // ==================================================================

    #[test]
    fn test_emit_effect_pure() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_effect(&Effect::Pure).unwrap(), "");
    }

    #[test]
    fn test_emit_effect_async() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_effect(&Effect::Async).unwrap(), "await ");
    }

    #[test]
    fn test_emit_effect_impure() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_effect(&Effect::Impure).unwrap(), "");
    }

    // ==================================================================
    // Type emission — delegates to TypeScriptMapper
    // ==================================================================

    #[test]
    fn test_emit_type_int() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(
            backend.emit_type(&Type::Named("Int".into())).unwrap(),
            "number"
        );
    }

    #[test]
    fn test_emit_type_string() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(
            backend.emit_type(&Type::Named("String".into())).unwrap(),
            "string"
        );
    }

    #[test]
    fn test_emit_type_record() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let ty = Type::Record(vec![
            ("x".into(), Box::new(Type::Named("Int".into()))),
            ("y".into(), Box::new(Type::Named("Int".into()))),
        ]);
        assert_eq!(backend.emit_type(&ty).unwrap(), "{ x: number; y: number }");
    }

    // ==================================================================
    // Expression emission — every LirExpr variant
    // ==================================================================

    #[test]
    fn test_emit_expr_literal() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Literal {
            value: LirLiteral::Int(42),
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "42");
    }

    #[test]
    fn test_emit_expr_variable() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Variable {
            name: "x".into(),
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "x");
    }

    #[test]
    fn test_emit_expr_call() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Call {
            func: Box::new(LirExpr::Variable {
                name: "f".into(),
                hint: hint_none(),
                span: s(),
            }),
            args: vec![
                LirExpr::Variable {
                    name: "x".into(),
                    hint: hint_none(),
                    span: s(),
                },
                LirExpr::Literal {
                    value: LirLiteral::Int(1),
                    hint: hint_none(),
                    span: s(),
                },
            ],
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "f(x, 1)");
    }

    #[test]
    fn test_emit_expr_call_async() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Call {
            func: Box::new(LirExpr::Variable {
                name: "f".into(),
                hint: hint_none(),
                span: s(),
            }),
            args: vec![LirExpr::Variable {
                name: "x".into(),
                hint: hint_none(),
                span: s(),
            }],
            hint: TargetHint::Async,
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "await f(x)");
    }

    #[test]
    fn test_emit_assert_single_arg() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Call {
            func: Box::new(LirExpr::Variable {
                name: "assert".into(),
                hint: TargetHint::None,
                span: s(),
            }),
            args: vec![LirExpr::Literal {
                value: LirLiteral::Bool(true),
                hint: TargetHint::None,
                span: s(),
            }],
            hint: TargetHint::None,
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "expect(true).toBe(true)");
    }

    #[test]
    fn test_emit_assert_eq_two_args() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Call {
            func: Box::new(LirExpr::Variable {
                name: "assert_eq".into(),
                hint: TargetHint::None,
                span: s(),
            }),
            args: vec![
                LirExpr::Literal {
                    value: LirLiteral::Int(42),
                    hint: TargetHint::None,
                    span: s(),
                },
                LirExpr::Literal {
                    value: LirLiteral::Int(42),
                    hint: TargetHint::None,
                    span: s(),
                },
            ],
            hint: TargetHint::None,
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "expect(42).toBe(42)");
    }

    #[test]
    fn test_emit_regular_call_unaffected() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Call {
            func: Box::new(LirExpr::Variable {
                name: "foo".into(),
                hint: TargetHint::None,
                span: s(),
            }),
            args: vec![LirExpr::Literal {
                value: LirLiteral::Int(1),
                hint: TargetHint::None,
                span: s(),
            }],
            hint: TargetHint::None,
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "foo(1)");
    }

    #[test]
    fn test_emit_assert_with_variable_arg() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Call {
            func: Box::new(LirExpr::Variable {
                name: "assert".into(),
                hint: TargetHint::None,
                span: s(),
            }),
            args: vec![LirExpr::Variable {
                name: "result".into(),
                hint: TargetHint::None,
                span: s(),
            }],
            hint: TargetHint::None,
            span: s(),
        };
        assert_eq!(
            backend.emit_expr(&expr).unwrap(),
            "expect(result).toBe(true)"
        );
    }

    #[test]
    fn test_emit_assert_eq_with_expressions() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Call {
            func: Box::new(LirExpr::Variable {
                name: "assert_eq".into(),
                hint: TargetHint::None,
                span: s(),
            }),
            args: vec![
                LirExpr::Binary {
                    op: LirBinaryOp::Add,
                    lhs: Box::new(LirExpr::Literal {
                        value: LirLiteral::Int(1),
                        hint: TargetHint::None,
                        span: s(),
                    }),
                    rhs: Box::new(LirExpr::Literal {
                        value: LirLiteral::Int(2),
                        hint: TargetHint::None,
                        span: s(),
                    }),
                    hint: TargetHint::None,
                    span: s(),
                },
                LirExpr::Literal {
                    value: LirLiteral::Int(3),
                    hint: TargetHint::None,
                    span: s(),
                },
            ],
            hint: TargetHint::None,
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "expect(1 + 2).toBe(3)");
    }

    #[test]
    fn test_emit_expr_member() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Member {
            obj: Box::new(LirExpr::Variable {
                name: "obj".into(),
                hint: hint_none(),
                span: s(),
            }),
            field: "field".into(),
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "obj.field");
    }

    #[test]
    fn test_emit_expr_member_optional() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Member {
            obj: Box::new(LirExpr::Variable {
                name: "obj".into(),
                hint: hint_none(),
                span: s(),
            }),
            field: "field".into(),
            hint: TargetHint::Optional,
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "obj?.field");
    }

    #[test]
    fn test_emit_expr_if_ternary() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::If {
            cond: Box::new(LirExpr::Variable {
                name: "cond".into(),
                hint: hint_none(),
                span: s(),
            }),
            then: Box::new(LirExpr::Variable {
                name: "thenVal".into(),
                hint: hint_none(),
                span: s(),
            }),
            else_: Some(Box::new(LirExpr::Variable {
                name: "elseVal".into(),
                hint: hint_none(),
                span: s(),
            })),
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(
            backend.emit_expr(&expr).unwrap(),
            "cond ? thenVal : elseVal"
        );
    }

    #[test]
    fn test_emit_expr_if_no_else() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::If {
            cond: Box::new(LirExpr::Literal {
                value: LirLiteral::Bool(false),
                hint: hint_none(),
                span: s(),
            }),
            then: Box::new(LirExpr::Variable {
                name: "thenVal".into(),
                hint: hint_none(),
                span: s(),
            }),
            else_: None,
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "thenVal");
    }

    #[test]
    fn test_emit_expr_match() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Match {
            expr: Box::new(LirExpr::Variable {
                name: "x".into(),
                hint: hint_none(),
                span: s(),
            }),
            arms: vec![
                LirArm {
                    pattern: LirPat::Literal(LirLiteral::Int(1)),
                    guard: None,
                    body: LirExpr::Literal {
                        value: LirLiteral::Str("one".into()),
                        hint: hint_none(),
                        span: s(),
                    },
                },
                LirArm {
                    pattern: LirPat::Wildcard,
                    guard: None,
                    body: LirExpr::Literal {
                        value: LirLiteral::Str("other".into()),
                        hint: hint_none(),
                        span: s(),
                    },
                },
            ],
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(
            backend.emit_expr(&expr).unwrap(),
            "x === 1 ? \"one\" : \"other\""
        );
    }

    #[test]
    fn test_emit_expr_block() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Block {
            stmts: vec![
                LirStmt::Let {
                    pat: LirPat::Variable("x".into()),
                    value: LirExpr::Literal {
                        value: LirLiteral::Int(1),
                        hint: hint_none(),
                        span: s(),
                    },
                },
                LirStmt::Expr(LirExpr::Variable {
                    name: "x".into(),
                    hint: hint_none(),
                    span: s(),
                }),
            ],
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(
            backend.emit_expr(&expr).unwrap(),
            "{ let x = 1; return x; }"
        );
    }

    #[test]
    fn test_emit_expr_assign() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Assign {
            target: Box::new(LirExpr::Variable {
                name: "x".into(),
                hint: hint_none(),
                span: s(),
            }),
            value: Box::new(LirExpr::Literal {
                value: LirLiteral::Int(42),
                hint: hint_none(),
                span: s(),
            }),
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "x = 42");
    }

    #[test]
    fn test_emit_expr_lambda() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Lambda {
            params: vec![
                LirParam {
                    name: "a".into(),
                    type_: Some(Type::Named("Int".into())),
                },
                LirParam {
                    name: "b".into(),
                    type_: None,
                },
            ],
            body: Box::new(LirExpr::Binary {
                op: LirBinaryOp::Add,
                lhs: Box::new(LirExpr::Variable {
                    name: "a".into(),
                    hint: hint_none(),
                    span: s(),
                }),
                rhs: Box::new(LirExpr::Variable {
                    name: "b".into(),
                    hint: hint_none(),
                    span: s(),
                }),
                hint: hint_none(),
                span: s(),
            }),
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "(a: number, b) => a + b");
    }

    #[test]
    fn test_emit_expr_record() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Record {
            fields: vec![
                (
                    "x".into(),
                    LirExpr::Literal {
                        value: LirLiteral::Int(1),
                        hint: hint_none(),
                        span: s(),
                    },
                ),
                (
                    "y".into(),
                    LirExpr::Literal {
                        value: LirLiteral::Str("hello".into()),
                        hint: hint_none(),
                        span: s(),
                    },
                ),
            ],
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "{ x: 1, y: \"hello\" }");
    }

    #[test]
    fn test_emit_expr_variant_no_arg() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Variant {
            name: "None".into(),
            arg: None,
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "\"None\"");
    }

    #[test]
    fn test_emit_expr_variant_with_arg() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Variant {
            name: "Ok".into(),
            arg: Some(Box::new(LirExpr::Literal {
                value: LirLiteral::Int(42),
                hint: hint_none(),
                span: s(),
            })),
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(
            backend.emit_expr(&expr).unwrap(),
            "{ tag: \"Ok\", value: 42 }"
        );
    }

    #[test]
    fn test_emit_expr_array() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Array {
            items: vec![
                LirExpr::Literal {
                    value: LirLiteral::Int(1),
                    hint: hint_none(),
                    span: s(),
                },
                LirExpr::Literal {
                    value: LirLiteral::Int(2),
                    hint: hint_none(),
                    span: s(),
                },
                LirExpr::Literal {
                    value: LirLiteral::Int(3),
                    hint: hint_none(),
                    span: s(),
                },
            ],
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "[1, 2, 3]");
    }

    #[test]
    fn test_emit_expr_binary() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Binary {
            op: LirBinaryOp::Add,
            lhs: Box::new(LirExpr::Variable {
                name: "a".into(),
                hint: hint_none(),
                span: s(),
            }),
            rhs: Box::new(LirExpr::Variable {
                name: "b".into(),
                hint: hint_none(),
                span: s(),
            }),
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "a + b");
    }

    #[test]
    fn test_emit_expr_binary_eq() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Binary {
            op: LirBinaryOp::Eq,
            lhs: Box::new(LirExpr::Variable {
                name: "a".into(),
                hint: hint_none(),
                span: s(),
            }),
            rhs: Box::new(LirExpr::Variable {
                name: "b".into(),
                hint: hint_none(),
                span: s(),
            }),
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "a === b");
    }

    #[test]
    fn test_emit_expr_unary_neg() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Unary {
            op: LirUnaryOp::Neg,
            expr: Box::new(LirExpr::Variable {
                name: "x".into(),
                hint: hint_none(),
                span: s(),
            }),
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "-x");
    }

    #[test]
    fn test_emit_expr_unary_not() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Unary {
            op: LirUnaryOp::Not,
            expr: Box::new(LirExpr::Variable {
                name: "flag".into(),
                hint: hint_none(),
                span: s(),
            }),
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "!flag");
    }

    #[test]
    fn test_emit_expr_wildcard() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let expr = LirExpr::Wildcard {
            hint: hint_none(),
            span: s(),
        };
        assert_eq!(backend.emit_expr(&expr).unwrap(), "_");
    }

    // ==================================================================
    // Pattern emission — all LirPat variants
    // ==================================================================

    #[test]
    fn test_emit_pat_wildcard() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_pat(&LirPat::Wildcard).unwrap(), "_");
    }

    #[test]
    fn test_emit_pat_literal() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let result = backend
            .emit_pat(&LirPat::Literal(LirLiteral::Int(42)))
            .unwrap();
        assert_eq!(result, "42");
    }

    #[test]
    fn test_emit_pat_variable() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let result = backend.emit_pat(&LirPat::Variable("myVar".into())).unwrap();
        assert_eq!(result, "myVar");
    }

    #[test]
    fn test_emit_pat_variant_no_arg() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let pat = LirPat::Variant {
            name: "None".into(),
            arg: None,
        };
        assert_eq!(backend.emit_pat(&pat).unwrap(), "None");
    }

    #[test]
    fn test_emit_pat_variant_with_arg() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let pat = LirPat::Variant {
            name: "Some".into(),
            arg: Some(Box::new(LirPat::Variable("inner".into()))),
        };
        assert_eq!(backend.emit_pat(&pat).unwrap(), "Some: inner");
    }

    #[test]
    fn test_emit_pat_record_no_rest() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let pat = LirPat::Record {
            fields: vec![("x".into(), LirPat::Wildcard)],
            rest: false,
        };
        assert_eq!(backend.emit_pat(&pat).unwrap(), "{ x: _ }");
    }

    #[test]
    fn test_emit_pat_record_with_rest() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let pat = LirPat::Record {
            fields: vec![("x".into(), LirPat::Wildcard)],
            rest: true,
        };
        assert_eq!(backend.emit_pat(&pat).unwrap(), "{ x: _, ... }");
    }

    #[test]
    fn test_emit_pat_record_empty() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let pat = LirPat::Record {
            fields: vec![],
            rest: false,
        };
        assert_eq!(backend.emit_pat(&pat).unwrap(), "{  }");
    }

    #[test]
    fn test_emit_pat_nested_variant_in_record() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let pat = LirPat::Record {
            fields: vec![(
                "opt".into(),
                LirPat::Variant {
                    name: "Some".into(),
                    arg: Some(Box::new(LirPat::Variable("val".into()))),
                },
            )],
            rest: false,
        };
        assert_eq!(backend.emit_pat(&pat).unwrap(), "{ opt: Some: val }");
    }

    // ==================================================================
    // Declaration emission
    // ==================================================================

    #[test]
    fn test_emit_decl_function() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::Function {
            name: "main".into(),
            params: vec![],
            return_type: Some(Type::Named("Void".into())),
            body: LirExpr::Literal {
                value: LirLiteral::Int(0),
                hint: hint_none(),
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::None,
            is_pub: true,
            span: s(),
        };
        assert_eq!(
            backend.emit_decl(&decl).unwrap(),
            "export function main(): void { return 0; }"
        );
    }

    #[test]
    fn test_emit_decl_function_async() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::Function {
            name: "fetchData".into(),
            params: vec![LirParam {
                name: "url".into(),
                type_: Some(Type::Named("String".into())),
            }],
            return_type: Some(Type::Generic {
                base: "Promise".into(),
                args: vec![Type::Named("String".into())],
            }),
            body: LirExpr::Literal {
                value: LirLiteral::Null,
                hint: TargetHint::Async,
                span: s(),
            },
            effect: Effect::Async,
            hint: TargetHint::Async,
            is_pub: true,
            span: s(),
        };
        let result = backend.emit_decl(&decl).unwrap();
        assert!(result.starts_with("export async function fetchData"));
        assert!(result.contains("url: string"));
        assert!(result.contains("Promise<string>"));
    }

    #[test]
    fn test_emit_decl_record() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::RecordDef {
            name: "Point".into(),
            fields: vec![
                LirField {
                    name: "x".into(),
                    type_: Type::Named("Int".into()),
                },
                LirField {
                    name: "y".into(),
                    type_: Type::Named("Int".into()),
                },
            ],
            is_pub: true,
            span: s(),
        };
        assert_eq!(
            backend.emit_decl(&decl).unwrap(),
            "export interface Point { x: number; y: number; }"
        );
    }

    #[test]
    fn test_emit_decl_union() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::UnionDef {
            name: "Option".into(),
            variants: vec![
                LirVariant {
                    name: "Some".into(),
                    arg: Some(Type::Named("Int".into())),
                },
                LirVariant {
                    name: "None".into(),
                    arg: None,
                },
            ],
            is_pub: true,
            span: s(),
        };
        assert_eq!(
            backend.emit_decl(&decl).unwrap(),
            "export type Option = Some | None;"
        );
    }

    #[test]
    fn test_emit_decl_function_with_params() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::Function {
            name: "add".into(),
            params: vec![
                LirParam {
                    name: "a".into(),
                    type_: Some(Type::Named("Int".into())),
                },
                LirParam {
                    name: "b".into(),
                    type_: Some(Type::Named("Int".into())),
                },
            ],
            return_type: Some(Type::Named("Int".into())),
            body: LirExpr::Binary {
                op: LirBinaryOp::Add,
                lhs: Box::new(LirExpr::Variable {
                    name: "a".into(),
                    hint: hint_none(),
                    span: s(),
                }),
                rhs: Box::new(LirExpr::Variable {
                    name: "b".into(),
                    hint: hint_none(),
                    span: s(),
                }),
                hint: hint_none(),
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::None,
            is_pub: true,
            span: s(),
        };
        assert_eq!(
            backend.emit_decl(&decl).unwrap(),
            "export function add(a: number, b: number): number { return a + b; }"
        );
    }

    // ==================================================================
    // Module emission
    // ==================================================================

    #[test]
    fn test_emit_module_empty() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        assert_eq!(backend.emit_module(&[]).unwrap(), "");
    }

    #[test]
    fn test_emit_module_single_function() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::Function {
            name: "main".into(),
            params: vec![],
            return_type: Some(Type::Named("Void".into())),
            body: LirExpr::Literal {
                value: LirLiteral::Int(0),
                hint: hint_none(),
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::None,
            is_pub: true,
            span: s(),
        };
        let result = backend.emit_module(&[decl]).unwrap();
        assert!(result.contains("function main"));
    }

    #[test]
    fn test_emit_module_mixed() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let func_decl = LirDecl::Function {
            name: "getOrigin".into(),
            params: vec![],
            return_type: None,
            body: LirExpr::Literal {
                value: LirLiteral::Null,
                hint: hint_none(),
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::None,
            is_pub: true,
            span: s(),
        };
        let record_decl = LirDecl::RecordDef {
            name: "Point".into(),
            fields: vec![
                LirField {
                    name: "x".into(),
                    type_: Type::Named("Int".into()),
                },
                LirField {
                    name: "y".into(),
                    type_: Type::Named("Int".into()),
                },
            ],
            is_pub: true,
            span: s(),
        };
        let result = backend.emit_module(&[record_decl, func_decl]).unwrap();
        assert!(result.contains("interface Point"));
        assert!(result.contains("function getOrigin"));
    }

    #[test]
    fn test_emit_module_includes_header() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::Function {
            name: "dummy".into(),
            params: vec![],
            return_type: None,
            body: LirExpr::Literal {
                value: LirLiteral::Null,
                hint: hint_none(),
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::None,
            is_pub: true,
            span: s(),
        };
        let result = backend.emit_module(&[decl]).unwrap();
        let first_line = result.lines().next().unwrap_or("");
        assert!(
            first_line.starts_with("// Generated by Dwarf"),
            "module output should start with the generated header, got: {first_line:?}"
        );
    }

    #[test]
    fn test_emit_module_header_has_version() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::Function {
            name: "dummy".into(),
            params: vec![],
            return_type: None,
            body: LirExpr::Literal {
                value: LirLiteral::Null,
                hint: hint_none(),
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::None,
            is_pub: true,
            span: s(),
        };
        let result = backend.emit_module(&[decl]).unwrap();
        let first_line = result.lines().next().unwrap_or("");
        assert!(
            first_line.contains("v0.1.0"),
            "header should contain the version string 'v0.1.0', got: {first_line:?}"
        );
    }

    #[test]
    fn test_emit_module_header_before_imports() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        backend.add_import("fs", "readFile");
        let decl = LirDecl::Function {
            name: "load".into(),
            params: vec![],
            return_type: None,
            body: LirExpr::Literal {
                value: LirLiteral::Null,
                hint: hint_none(),
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::None,
            is_pub: true,
            span: s(),
        };
        let result = backend.emit_module(&[decl]).unwrap();
        let lines: Vec<&str> = result.lines().collect();
        assert!(
            lines.len() >= 3,
            "should have header line + blank + import + ... , got {lines:?}"
        );
        assert!(
            lines[0].starts_with("// Generated by Dwarf"),
            "first line should be the generated header"
        );
        assert!(
            lines[1].is_empty(),
            "second line should be blank after header"
        );
        assert!(
            lines[2].contains("import { readFile } from 'fs'"),
            "third line should be the import statement"
        );
    }

    // ==================================================================
    // Import integration — ImportManager wired into emit_module
    // ==================================================================

    #[test]
    fn test_emit_module_with_imports() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        backend.add_import("react", "useState");
        backend.add_import("react", "useEffect");
        let decl = LirDecl::Function {
            name: "myHook".into(),
            params: vec![],
            return_type: None,
            body: LirExpr::Literal {
                value: LirLiteral::Null,
                hint: hint_none(),
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::None,
            is_pub: true,
            span: s(),
        };
        let result = backend.emit_module(&[decl]).unwrap();
        assert!(
            result.contains("import { useEffect } from 'react'\nimport { useState } from 'react'"),
            "module should contain the import statements, got: {result:?}"
        );
        assert!(
            result.contains("export function myHook"),
            "module should contain the function declaration"
        );
        // Verify header comes before imports
        let lines: Vec<&str> = result.lines().collect();
        assert!(
            lines[0].starts_with("// Generated by Dwarf"),
            "header should be first, got: {:?}",
            lines[0]
        );
    }

    #[test]
    fn test_emit_import_string_format() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        backend.add_import("fs", "readFile");
        let imports = backend.imports.emit_imports();
        assert_eq!(imports.len(), 1);
        assert_eq!(imports[0], "import { readFile } from 'fs'");
    }

    #[test]
    fn test_add_import_then_emit() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        backend.add_import("lodash", "map");
        let result = backend.emit_module(&[]).unwrap();
        assert!(
            result.contains("import { map } from 'lodash'"),
            "module should contain the import line, got: {result:?}"
        );
    }

    #[test]
    fn test_imports_at_top() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        backend.add_import("http", "createServer");
        let decl = LirDecl::Function {
            name: "start".into(),
            params: vec![],
            return_type: None,
            body: LirExpr::Literal {
                value: LirLiteral::Null,
                hint: hint_none(),
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::None,
            is_pub: false,
            span: s(),
        };
        let result = backend.emit_module(&[decl]).unwrap();
        let lines: Vec<&str> = result.lines().collect();
        assert!(
            lines.len() >= 4,
            "should have header + blank + import + blank + decl, got {lines:?}"
        );
        // Line 0: header
        assert!(
            lines[0].starts_with("// Generated by Dwarf"),
            "first line should be header"
        );
        // Line 1: blank after header
        assert!(lines[1].is_empty(), "line 1 should be blank separator");
        // Line 2: import
        assert_eq!(lines[2], "import { createServer } from 'http'");
        // Line 3: blank between import and declarations
        assert!(lines[3].is_empty(), "line 3 should be blank separator");
        // Line 4: declaration
        assert!(
            lines[4].contains("function start"),
            "line 4 should contain the declaration"
        );
    }

    #[test]
    fn test_no_imports_no_import_lines() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::Function {
            name: "noop".into(),
            params: vec![],
            return_type: None,
            body: LirExpr::Literal {
                value: LirLiteral::Null,
                hint: hint_none(),
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::None,
            is_pub: false,
            span: s(),
        };
        let result = backend.emit_module(&[decl]).unwrap();
        assert!(!result.contains("import "), "should not emit import lines");
        assert!(result.contains("function noop"));
    }

    // ==================================================================
    // Export support — is_pub handling in emit_decl
    // ==================================================================

    #[test]
    fn test_emit_private_function_not_exported() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::Function {
            name: "helper".into(),
            params: vec![],
            return_type: None,
            body: LirExpr::Literal {
                value: LirLiteral::Int(0),
                hint: hint_none(),
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::None,
            is_pub: false,
            span: s(),
        };
        let result = backend.emit_decl(&decl).unwrap();
        assert!(
            !result.starts_with("export "),
            "private function should not have export prefix, got: {result:?}"
        );
        assert!(
            result.starts_with("function helper"),
            "private function should start with 'function', got: {result:?}"
        );
    }

    #[test]
    fn test_emit_public_record_exported() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::RecordDef {
            name: "Point".into(),
            fields: vec![
                LirField {
                    name: "x".into(),
                    type_: Type::Named("Int".into()),
                },
                LirField {
                    name: "y".into(),
                    type_: Type::Named("Int".into()),
                },
            ],
            is_pub: true,
            span: s(),
        };
        let result = backend.emit_decl(&decl).unwrap();
        assert!(
            result.starts_with("export interface"),
            "public record should have 'export interface', got: {result:?}"
        );
    }

    #[test]
    fn test_emit_private_record_not_exported() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::RecordDef {
            name: "Internal".into(),
            fields: vec![LirField {
                name: "secret".into(),
                type_: Type::Named("String".into()),
            }],
            is_pub: false,
            span: s(),
        };
        let result = backend.emit_decl(&decl).unwrap();
        assert!(
            !result.starts_with("export "),
            "private record should not have export prefix, got: {result:?}"
        );
        assert!(
            result.starts_with("interface Internal"),
            "private record should start with 'interface', got: {result:?}"
        );
    }

    #[test]
    fn test_emit_public_union_exported() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::UnionDef {
            name: "Option".into(),
            variants: vec![
                LirVariant {
                    name: "Some".into(),
                    arg: Some(Type::Named("Int".into())),
                },
                LirVariant {
                    name: "None".into(),
                    arg: None,
                },
            ],
            is_pub: true,
            span: s(),
        };
        let result = backend.emit_decl(&decl).unwrap();
        assert!(
            result.starts_with("export type Option"),
            "public union should have 'export type', got: {result:?}"
        );
    }

    #[test]
    fn test_emit_private_union_not_exported() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::UnionDef {
            name: "InternalOpt".into(),
            variants: vec![LirVariant {
                name: "Val".into(),
                arg: None,
            }],
            is_pub: false,
            span: s(),
        };
        let result = backend.emit_decl(&decl).unwrap();
        assert!(
            !result.starts_with("export "),
            "private union should not have export prefix, got: {result:?}"
        );
        assert!(
            result.starts_with("type InternalOpt"),
            "private union should start with 'type', got: {result:?}"
        );
    }

    #[test]
    fn test_emit_module_public_decls_exported() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let pub_fn = LirDecl::Function {
            name: "publicFn".into(),
            params: vec![],
            return_type: None,
            body: LirExpr::Literal {
                value: LirLiteral::Null,
                hint: hint_none(),
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::None,
            is_pub: true,
            span: s(),
        };
        let priv_fn = LirDecl::Function {
            name: "privateHelper".into(),
            params: vec![],
            return_type: None,
            body: LirExpr::Literal {
                value: LirLiteral::Null,
                hint: hint_none(),
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::None,
            is_pub: false,
            span: s(),
        };
        let result = backend.emit_module(&[pub_fn, priv_fn]).unwrap();
        assert!(
            result.contains("export function publicFn"),
            "public function should be exported"
        );
        assert!(
            result.contains("function privateHelper"),
            "private function should NOT be exported"
        );
        // Ensure the private function does NOT have export prefix
        for line in result.lines() {
            if line.contains("privateHelper") {
                assert!(
                    !line.contains("export "),
                    "private helper line should not contain 'export', got: {line:?}"
                );
            }
        }
    }

    // ==================================================================
    // JSX / React Component emission
    // ==================================================================

    #[test]
    fn test_emit_component_simple() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::Function {
            name: "Button".into(),
            params: vec![],
            return_type: None,
            body: LirExpr::Literal {
                value: LirLiteral::Str("Click me".into()),
                hint: TargetHint::None,
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::ReactComponent,
            is_pub: true,
            span: s(),
        };
        let result = backend.emit_decl(&decl).unwrap();
        assert!(result.contains("React.FC"));
        assert!(result.contains("Button"));
        assert!(result.contains("const Button"));
    }

    #[test]
    fn test_emit_component_with_props() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::Function {
            name: "Greeting".into(),
            params: vec![LirParam {
                name: "name".into(),
                type_: Some(Type::Named("String".into())),
            }],
            return_type: None,
            body: LirExpr::Literal {
                value: LirLiteral::Str("Hello".into()),
                hint: TargetHint::None,
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::ReactComponent,
            is_pub: true,
            span: s(),
        };
        let result = backend.emit_decl(&decl).unwrap();
        assert!(result.contains("React.FC<GreetingProps>"));
        assert!(result.contains("name: string"));
    }

    #[test]
    fn test_emit_regular_function_not_affected() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::Function {
            name: "helper".into(),
            params: vec![],
            return_type: None,
            body: LirExpr::Literal {
                value: LirLiteral::Int(42),
                hint: TargetHint::None,
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::None,
            is_pub: true,
            span: s(),
        };
        let result = backend.emit_decl(&decl).unwrap();
        assert!(result.starts_with("export function"));
        assert!(!result.contains("React.FC"));
    }

    #[test]
    fn test_emit_component_private() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let decl = LirDecl::Function {
            name: "Internal".into(),
            params: vec![],
            return_type: None,
            body: LirExpr::Literal {
                value: LirLiteral::Null,
                hint: TargetHint::None,
                span: s(),
            },
            effect: Effect::Pure,
            hint: TargetHint::ReactComponent,
            is_pub: false,
            span: s(),
        };
        let result = backend.emit_decl(&decl).unwrap();
        assert!(!result.starts_with("export"));
        assert!(result.starts_with("const Internal"));
    }

    #[test]
    fn test_emit_component_with_jsx_body() {
        let mut backend = TypeScriptBackend::new("0.1.0");
        let body = LirExpr::Record {
            fields: vec![
                (
                    "__tag".into(),
                    LirExpr::Literal {
                        value: LirLiteral::Str("div".into()),
                        hint: TargetHint::None,
                        span: s(),
                    },
                ),
                (
                    "className".into(),
                    LirExpr::Literal {
                        value: LirLiteral::Str("container".into()),
                        hint: TargetHint::None,
                        span: s(),
                    },
                ),
            ],
            hint: TargetHint::ReactComponent,
            span: s(),
        };
        let decl = LirDecl::Function {
            name: "Container".into(),
            params: vec![],
            return_type: None,
            body,
            effect: Effect::Pure,
            hint: TargetHint::ReactComponent,
            is_pub: true,
            span: s(),
        };
        let result = backend.emit_decl(&decl).unwrap();
        assert!(result.contains("React.FC"));
    }
}
