//! Integration tests for the Java backend.
//!
//! Each test constructs a complete LIR program (one or more declarations),
//! emits it through [`JavaBackend`], and verifies the Java output matches
//! the expected form.
//!
//! All tests should **fail** during the RED phase because the JavaBackend
//! stub returns `UnsupportedFeature` for every method.

use dwarf_emitter::backend::EmitterBackend;
use dwarf_emitter::java::backend::JavaBackend;
use dwarf_lir::{
    Effect, LirArm, LirBinaryOp, LirDecl, LirExpr, LirField, LirLiteral, LirParam, LirPat, LirStmt,
    LirUnaryOp, LirVariant, TargetHint,
};
use dwarf_syntax::hir::Type;
use dwarf_syntax::span::Span;

// ------------------------------------------------------------------
// Helpers
// ------------------------------------------------------------------

fn s() -> Span {
    Span::new(0, 0, 0)
}

fn no_hint() -> TargetHint {
    TargetHint::None
}

fn int_lit(v: i64) -> LirExpr {
    LirExpr::Literal {
        value: LirLiteral::Int(v),
        hint: no_hint(),
        span: s(),
    }
}

fn float_lit(v: f64) -> LirExpr {
    LirExpr::Literal {
        value: LirLiteral::Float(v),
        hint: no_hint(),
        span: s(),
    }
}

fn str_lit(v: &str) -> LirExpr {
    LirExpr::Literal {
        value: LirLiteral::Str(v.to_string()),
        hint: no_hint(),
        span: s(),
    }
}

fn bool_lit(v: bool) -> LirExpr {
    LirExpr::Literal {
        value: LirLiteral::Bool(v),
        hint: no_hint(),
        span: s(),
    }
}

fn null_lit() -> LirExpr {
    LirExpr::Literal {
        value: LirLiteral::Null,
        hint: no_hint(),
        span: s(),
    }
}

fn var(name: &str) -> LirExpr {
    LirExpr::Variable {
        name: name.to_string(),
        hint: no_hint(),
        span: s(),
    }
}

fn param(name: &str, type_: Option<Type>) -> LirParam {
    LirParam {
        name: name.to_string(),
        type_,
    }
}

fn emit_program(decls: Vec<LirDecl>) -> String {
    let mut backend = JavaBackend::default();
    backend.emit_module(&decls).unwrap()
}

// ==================================================================
// Section 1: Basic function emission
// ==================================================================

#[test]
fn test_java_empty_module() {
    let result = emit_program(vec![]);
    assert_eq!(result, "", "empty module should produce empty string");
}

#[test]
fn test_java_simple_function() {
    // Expected Java output:
    // // Generated by Dwarf v0.1.0 — edit source, not this file
    //
    // public class Main {
    //     public static int main() {
    //         return 42;
    //     }
    // }
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: int_lit(42),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    // Must emit a class wrapper with a static method
    assert!(
        result.contains("public class Main"),
        "should contain class definition"
    );
    assert!(result.contains("public static"), "method should be static");
    assert!(result.contains("main"), "should contain method name");
    assert!(result.contains("42"), "should contain the return value");
}

#[test]
fn test_java_private_function() {
    // Private functions in Java use no `public` modifier (package-private).
    let decl = LirDecl::Function {
        name: "helper".into(),
        params: vec![],
        return_type: None,
        body: null_lit(),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("class"), "should contain class definition");
    assert!(result.contains("helper"), "should contain method name");
}

#[test]
fn test_java_function_with_params() {
    // Expected: public static int add(int a, int b) { return a + b; }
    let decl = LirDecl::Function {
        name: "add".into(),
        params: vec![
            param("a", Some(Type::Named("Int".into()))),
            param("b", Some(Type::Named("Int".into()))),
        ],
        return_type: Some(Type::Named("Int".into())),
        body: LirExpr::Binary {
            op: LirBinaryOp::Add,
            lhs: Box::new(var("a")),
            rhs: Box::new(var("b")),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("int a"),
        "should contain parameter a with int type"
    );
    assert!(
        result.contains("int b"),
        "should contain parameter b with int type"
    );
    assert!(
        result.contains("add("),
        "should contain function name with parens"
    );
    assert!(
        result.contains("a + b") || result.contains("a+b"),
        "should contain add operation"
    );
}

#[test]
fn test_java_function_with_return_type() {
    // Expected: public static String greet(String name) { return name; }
    let decl = LirDecl::Function {
        name: "greet".into(),
        params: vec![param("name", Some(Type::Named("String".into())))],
        return_type: Some(Type::Named("String".into())),
        body: var("name"),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("String"), "should use Java String type");
    assert!(result.contains("name"), "should reference parameter name");
    assert!(result.contains("greet"), "should contain method name");
}

#[test]
fn test_java_function_multi_param() {
    // Expected: public static double calculate(double x, double y, String label)
    let decl = LirDecl::Function {
        name: "calculate".into(),
        params: vec![
            param("x", Some(Type::Named("Float".into()))),
            param("y", Some(Type::Named("Float".into()))),
            param("label", Some(Type::Named("String".into()))),
        ],
        return_type: Some(Type::Named("Float".into())),
        body: null_lit(),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("double x"), "Float should map to double");
    assert!(result.contains("double y"), "Float should map to double");
    assert!(
        result.contains("String label"),
        "String should stay as String"
    );
    assert!(
        result.contains("calculate("),
        "should contain method name with parens"
    );
}

// ==================================================================
// Section 2: Type declarations
// ==================================================================

#[test]
fn test_java_record_def() {
    // Expected: public record Point(int x, int y) { }
    let decl = LirDecl::RecordDef {
        name: "Point".into(),
        fields: vec![
            LirField {
                name: "x".into(),
                type_: Type::Named("Int".into()),
            },
            LirField {
                name: "y".into(),
                type_: Type::Named("Int".into()),
            },
        ],
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("record"),
        "Java should emit `record` keyword"
    );
    assert!(result.contains("Point"), "should contain record name");
    assert!(
        result.contains("int x"),
        "should contain field x with int type"
    );
    assert!(
        result.contains("int y"),
        "should contain field y with int type"
    );
}

#[test]
fn test_java_union_def() {
    // Expected: public sealed interface Option permits Some, None { }
    let decl = LirDecl::UnionDef {
        name: "Option".into(),
        variants: vec![
            LirVariant {
                name: "Some".into(),
                arg: Some(Type::Named("Int".into())),
            },
            LirVariant {
                name: "None".into(),
                arg: None,
            },
        ],
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("sealed"), "Java unions use sealed types");
    assert!(
        result.contains("interface") || result.contains("class"),
        "sealed should be interface or class"
    );
    assert!(result.contains("Option"), "should contain union name");
    assert!(
        result.contains("permits") || result.contains("Permits"),
        "sealed should have permits clause"
    );
    assert!(
        result.contains("Some") && (result.contains("None") || result.contains("Empty")),
        "should contain variant names"
    );
}

#[test]
fn test_java_record_no_fields() {
    // Expected: public record Empty() { }
    let decl = LirDecl::RecordDef {
        name: "Empty".into(),
        fields: vec![],
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("record"), "should emit record keyword");
    assert!(result.contains("Empty"), "should contain record name");
}

#[test]
fn test_java_union_single_variant() {
    // A union with a single variant.
    let decl = LirDecl::UnionDef {
        name: "Wrapper".into(),
        variants: vec![LirVariant {
            name: "Value".into(),
            arg: Some(Type::Named("Int".into())),
        }],
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("Wrapper"), "should contain union type name");
    assert!(result.contains("Value"), "should contain variant name");
}

// ==================================================================
// Section 3: Literals and expressions
// ==================================================================

#[test]
fn test_java_literal_int() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: int_lit(42),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("42"), "int literal should emit 42");
}

#[test]
fn test_java_literal_float() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: float_lit(3.5),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("3.5"), "float literal should emit 3.5");
}

#[test]
fn test_java_literal_str() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: str_lit("hello"),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("\"hello\""),
        "string literal should be double-quoted"
    );
}

#[test]
fn test_java_literal_bool() {
    // Java uses lowercase true/false
    let decl_true = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: bool_lit(true),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result_true = emit_program(vec![decl_true]);
    assert!(
        result_true.contains("true"),
        "Java bool true should be lowercase"
    );

    let decl_false = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: bool_lit(false),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result_false = emit_program(vec![decl_false]);
    assert!(
        result_false.contains("false"),
        "Java bool false should be lowercase"
    );
}

#[test]
fn test_java_literal_null() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: null_lit(),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("null") && !result.contains("None"),
        "Java uses `null` not `None`"
    );
}

#[test]
fn test_java_variable() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![param("x", Some(Type::Named("Int".into())))],
        return_type: None,
        body: var("x"),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("x"),
        "variable reference should emit the name"
    );
}

// ==================================================================
// Section 4: Binary and unary operators
// ==================================================================

#[test]
fn test_java_binary_arithmetic() {
    // Test +, -, *, /
    let decl_add = LirDecl::Function {
        name: "calc".into(),
        params: vec![
            param("a", Some(Type::Named("Int".into()))),
            param("b", Some(Type::Named("Int".into()))),
        ],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Add,
            lhs: Box::new(var("a")),
            rhs: Box::new(var("b")),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl_add]);
    assert!(result.contains("a + b"), "Java uses `+` for addition");
}

#[test]
fn test_java_binary_sub() {
    let decl = LirDecl::Function {
        name: "sub".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Sub,
            lhs: Box::new(int_lit(10)),
            rhs: Box::new(int_lit(3)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("10 - 3"), "Java uses `-` for subtraction");
}

#[test]
fn test_java_binary_mul() {
    let decl = LirDecl::Function {
        name: "mul".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Mul,
            lhs: Box::new(int_lit(6)),
            rhs: Box::new(int_lit(7)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("6 * 7"), "Java uses `*` for multiplication");
}

#[test]
fn test_java_binary_div() {
    let decl = LirDecl::Function {
        name: "div".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Div,
            lhs: Box::new(int_lit(10)),
            rhs: Box::new(int_lit(2)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("10 / 2"), "Java uses `/` for division");
}

#[test]
fn test_java_binary_comparison() {
    // Test ==, !=, <, >, <=, >=
    let decl_eq = LirDecl::Function {
        name: "eq".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Eq,
            lhs: Box::new(int_lit(1)),
            rhs: Box::new(int_lit(2)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl_eq]);
    assert!(result.contains("1 == 2"), "Java uses `==` for equality");

    let decl_ne = LirDecl::Function {
        name: "ne".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Ne,
            lhs: Box::new(int_lit(1)),
            rhs: Box::new(int_lit(2)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result_ne = emit_program(vec![decl_ne]);
    assert!(result_ne.contains("1 != 2"), "Java uses `!=` for not-equal");
}

#[test]
fn test_java_binary_lt_gt() {
    let decl_lt = LirDecl::Function {
        name: "cmp_lt".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Lt,
            lhs: Box::new(int_lit(1)),
            rhs: Box::new(int_lit(2)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl_lt]);
    assert!(result.contains("1 < 2"), "Java uses `<` for less-than");

    let decl_gt = LirDecl::Function {
        name: "cmp_gt".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Gt,
            lhs: Box::new(int_lit(3)),
            rhs: Box::new(int_lit(2)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result_gt = emit_program(vec![decl_gt]);
    assert!(
        result_gt.contains("3 > 2"),
        "Java uses `>` for greater-than"
    );
}

#[test]
fn test_java_binary_le_ge() {
    let decl_le = LirDecl::Function {
        name: "cmp_le".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Le,
            lhs: Box::new(int_lit(1)),
            rhs: Box::new(int_lit(1)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl_le]);
    assert!(
        result.contains("1 <= 1"),
        "Java uses `<=` for less-or-equal"
    );
}

#[test]
fn test_java_binary_and_or() {
    let decl_and = LirDecl::Function {
        name: "logic_and".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::And,
            lhs: Box::new(bool_lit(true)),
            rhs: Box::new(bool_lit(false)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl_and]);
    assert!(result.contains("&&"), "Java uses `&&` for logical AND");

    let decl_or = LirDecl::Function {
        name: "logic_or".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Or,
            lhs: Box::new(bool_lit(true)),
            rhs: Box::new(bool_lit(false)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result_or = emit_program(vec![decl_or]);
    assert!(result_or.contains("||"), "Java uses `||` for logical OR");
}

#[test]
fn test_java_unary_neg() {
    let decl = LirDecl::Function {
        name: "negate".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Unary {
            op: LirUnaryOp::Neg,
            expr: Box::new(int_lit(5)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("-5") || result.contains("-(5)") || result.contains("-( 5 )"),
        "negation should produce `-5`"
    );
}

#[test]
fn test_java_unary_not() {
    let decl = LirDecl::Function {
        name: "invert".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Unary {
            op: LirUnaryOp::Not,
            expr: Box::new(bool_lit(true)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("!"), "Java uses `!` for logical NOT");
}

// ==================================================================
// Section 5: Control flow and complex expressions
// ==================================================================

#[test]
fn test_java_if_else_ternary() {
    // Java ternary: cond ? then : else
    let decl = LirDecl::Function {
        name: "max".into(),
        params: vec![
            param("a", Some(Type::Named("Int".into()))),
            param("b", Some(Type::Named("Int".into()))),
        ],
        return_type: None,
        body: LirExpr::If {
            cond: Box::new(LirExpr::Binary {
                op: LirBinaryOp::Gt,
                lhs: Box::new(var("a")),
                rhs: Box::new(var("b")),
                hint: no_hint(),
                span: s(),
            }),
            then: Box::new(var("a")),
            else_: Some(Box::new(var("b"))),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    // Java ternary: a > b ? a : b
    assert!(
        result.contains("?") && result.contains(":"),
        "Java if/else should emit ternary with `?` and `:`"
    );
    assert!(
        result.contains("a > b") || result.contains("a>b"),
        "should contain condition"
    );
}

#[test]
fn test_java_call_function() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Call {
            func: Box::new(var("add")),
            args: vec![int_lit(1), int_lit(2)],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("add(1, 2)") || result.contains("add(1,2)"),
        "should emit function call"
    );
}

#[test]
fn test_java_lambda() {
    // Java lambda: (x) -> x + 1
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Lambda {
            params: vec![LirParam {
                name: "x".into(),
                type_: None,
            }],
            body: Box::new(LirExpr::Binary {
                op: LirBinaryOp::Add,
                lhs: Box::new(var("x")),
                rhs: Box::new(int_lit(1)),
                hint: no_hint(),
                span: s(),
            }),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("->"), "Java lambdas use `->` syntax");
    assert!(result.contains("x"), "lambda should reference parameter");
}

#[test]
fn test_java_record_expr() {
    // Java new record expression: new Point(1, 2)
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Record {
            fields: vec![("x".into(), int_lit(1)), ("y".into(), int_lit(2))],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("new "),
        "Java record expression should use `new`"
    );
    assert!(
        result.contains("1") && result.contains("2"),
        "record expression should contain field values"
    );
}

#[test]
fn test_java_array_expr() {
    // Java array: new int[]{1, 2, 3}
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Array {
            items: vec![int_lit(1), int_lit(2), int_lit(3)],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("{") && result.contains("}"),
        "array should use curly braces"
    );
}

#[test]
fn test_java_block_with_let() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: Some(Type::Named("Int".into())),
        body: LirExpr::Block {
            stmts: vec![
                LirStmt::Let {
                    pat: LirPat::Variable("x".into()),
                    value: int_lit(1),
                },
                LirStmt::Expr(LirExpr::Binary {
                    op: LirBinaryOp::Add,
                    lhs: Box::new(var("x")),
                    rhs: Box::new(int_lit(1)),
                    hint: no_hint(),
                    span: s(),
                }),
            ],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("int x = 1") || result.contains("x = 1"),
        "block should contain variable assignment"
    );
    assert!(
        result.contains("x + 1"),
        "block should contain addition expression"
    );
}

// ==================================================================
// Section 6: Member access and chaining
// ==================================================================

#[test]
fn test_java_member_access() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Member {
            obj: Box::new(var("obj")),
            field: "field".into(),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("obj.field"),
        "member access should use dot notation"
    );
}

#[test]
fn test_java_member_call() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Call {
            func: Box::new(LirExpr::Member {
                obj: Box::new(var("obj")),
                field: "method".into(),
                hint: no_hint(),
                span: s(),
            }),
            args: vec![int_lit(42)],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("obj.method"),
        "member access should use dot notation"
    );
    assert!(result.contains("42"), "method call should pass arguments");
}

// ==================================================================
// Section 7: Pattern emission
// ==================================================================

#[test]
fn test_java_match_ternary() {
    let decl = LirDecl::Function {
        name: "label".into(),
        params: vec![param("x", Some(Type::Named("Int".into())))],
        return_type: None,
        body: LirExpr::Match {
            expr: Box::new(var("x")),
            arms: vec![
                LirArm {
                    pattern: LirPat::Literal(LirLiteral::Int(1)),
                    guard: None,
                    body: str_lit("one"),
                },
                LirArm {
                    pattern: LirPat::Wildcard,
                    guard: None,
                    body: str_lit("other"),
                },
            ],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    // Java match should emit ternary or switch expression
    assert!(
        result.contains("?") || result.contains("switch"),
        "match should emit ternary chain or switch expression"
    );
}

#[test]
fn test_java_pattern_wildcard() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Match {
            expr: Box::new(int_lit(0)),
            arms: vec![LirArm {
                pattern: LirPat::Wildcard,
                guard: None,
                body: null_lit(),
            }],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("default") || result.contains("_") || result.contains("else"),
        "wildcard pattern should emit default/else"
    );
}

// ==================================================================
// Section 8: Async / Optional / Result mapping
// ==================================================================

#[test]
fn test_java_async_function() {
    // Java CompletableFuture for async
    let decl = LirDecl::Function {
        name: "fetchData".into(),
        params: vec![param("url", Some(Type::Named("String".into())))],
        return_type: Some(Type::Generic {
            base: "CompletableFuture".into(),
            args: vec![Type::Named("String".into())],
        }),
        body: null_lit(),
        effect: Effect::Async,
        hint: TargetHint::Async,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("CompletableFuture"),
        "async should use CompletableFuture"
    );
    assert!(result.contains("fetchData"), "should contain function name");
}

#[test]
fn test_java_optional_hint() {
    // Optional<T> for optional values
    let decl = LirDecl::Function {
        name: "findUser".into(),
        params: vec![param("id", Some(Type::Named("Int".into())))],
        return_type: None,
        body: LirExpr::Literal {
            value: LirLiteral::Null,
            hint: TargetHint::Optional,
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    // Optional should use Optional.of() / Optional.empty()
    assert!(
        result.contains("Optional"),
        "optional hint should use Java Optional"
    );
}

// ==================================================================
// Section 9: Module-level emission
// ==================================================================

#[test]
fn test_java_module_header() {
    let decl = LirDecl::Function {
        name: "noop".into(),
        params: vec![],
        return_type: None,
        body: null_lit(),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    let first_line = result.lines().next().unwrap_or("");
    assert!(
        first_line.starts_with("// Generated by Dwarf"),
        "output should start with Java comment header, got: {first_line:?}"
    );
}

#[test]
fn test_java_mixed_module() {
    let record_decl = LirDecl::RecordDef {
        name: "Point".into(),
        fields: vec![
            LirField {
                name: "x".into(),
                type_: Type::Named("Int".into()),
            },
            LirField {
                name: "y".into(),
                type_: Type::Named("Int".into()),
            },
        ],
        is_pub: true,
        span: s(),
    };
    let func_decl = LirDecl::Function {
        name: "getOrigin".into(),
        params: vec![],
        return_type: None,
        body: null_lit(),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let union_decl = LirDecl::UnionDef {
        name: "Option".into(),
        variants: vec![
            LirVariant {
                name: "Some".into(),
                arg: Some(Type::Named("Int".into())),
            },
            LirVariant {
                name: "None".into(),
                arg: None,
            },
        ],
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![record_decl, func_decl, union_decl]);
    // Verify header
    assert!(
        result.starts_with("// Generated by Dwarf"),
        "should start with Java header"
    );
    // Verify all three declarations appear in order
    assert!(result.contains("Point"), "should contain Point");
    assert!(
        result.contains("getOrigin") || result.contains("get_origin"),
        "should contain getOrigin function"
    );
    assert!(
        result.contains("Option") || result.contains("Union"),
        "should contain Option union type"
    );
}

// ==================================================================
// Section 10: Edge cases
// ==================================================================

#[test]
fn test_java_no_trailing_whitespace() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: int_lit(42),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    // Last char should not be whitespace
    assert!(
        !result.ends_with(' ') && !result.ends_with('\n'),
        "output should not have trailing whitespace"
    );
}

#[test]
fn test_java_generic_type() {
    // Test that generic types emit correctly
    let decl = LirDecl::Function {
        name: "process".into(),
        params: vec![param(
            "items",
            Some(Type::Generic {
                base: "List".into(),
                args: vec![Type::Named("String".into())],
            }),
        )],
        return_type: Some(Type::Generic {
            base: "List".into(),
            args: vec![Type::Named("String".into())],
        }),
        body: null_lit(),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("List<"), "generics should use <> syntax");
    assert!(result.contains("String"), "should reference String type");
}

#[test]
fn test_java_empty_module_strict() {
    let mut backend = JavaBackend::default();
    let result = backend.emit_module(&[]).unwrap();
    assert_eq!(result, "", "empty module must produce empty string");
}
