//! Integration tests for the Python backend.
//!
//! Each test constructs a complete LIR program (one or more declarations),
//! emits it through [`PythonBackend`], and verifies the Python output
//! matches the expected form.
//!
//! All tests should **fail** during the RED phase because the PythonBackend
//! stub returns `UnsupportedFeature` for every method.

use dwarf_emitter::backend::EmitterBackend;
use dwarf_emitter::py::backend::PythonBackend;
use dwarf_lir::{
    Effect, LirArm, LirBinaryOp, LirDecl, LirExpr, LirField, LirLiteral, LirParam, LirPat, LirStmt,
    LirUnaryOp, LirVariant, TargetHint,
};
use dwarf_syntax::hir::Type;
use dwarf_syntax::span::Span;

// ------------------------------------------------------------------
// Helpers
// ------------------------------------------------------------------

fn s() -> Span {
    Span::new(0, 0, 0)
}

fn no_hint() -> TargetHint {
    TargetHint::None
}

fn int_lit(v: i64) -> LirExpr {
    LirExpr::Literal {
        value: LirLiteral::Int(v),
        hint: no_hint(),
        span: s(),
    }
}

fn float_lit(v: f64) -> LirExpr {
    LirExpr::Literal {
        value: LirLiteral::Float(v),
        hint: no_hint(),
        span: s(),
    }
}

fn str_lit(v: &str) -> LirExpr {
    LirExpr::Literal {
        value: LirLiteral::Str(v.to_string()),
        hint: no_hint(),
        span: s(),
    }
}

fn bool_lit(v: bool) -> LirExpr {
    LirExpr::Literal {
        value: LirLiteral::Bool(v),
        hint: no_hint(),
        span: s(),
    }
}

fn null_lit() -> LirExpr {
    LirExpr::Literal {
        value: LirLiteral::Null,
        hint: no_hint(),
        span: s(),
    }
}

fn var(name: &str) -> LirExpr {
    LirExpr::Variable {
        name: name.to_string(),
        hint: no_hint(),
        span: s(),
    }
}

fn param(name: &str, type_: Option<Type>) -> LirParam {
    LirParam {
        name: name.to_string(),
        type_,
    }
}

fn emit_program(decls: Vec<LirDecl>) -> String {
    let mut backend = PythonBackend::new();
    backend.emit_module(&decls).unwrap()
}

// ==================================================================
// Section 1: Basic function emission
// ==================================================================

#[test]
fn test_py_empty_module() {
    let result = emit_program(vec![]);
    assert_eq!(result, "", "empty module should produce empty string");
}

#[test]
fn test_py_simple_function() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: int_lit(42),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(result, "# Generated by Dwarf\n\ndef main():\n    return 42");
}

#[test]
fn test_py_private_function() {
    // Private functions have no `pub` equivalent in Python — no leading underscore
    // or special marker needed; they're simply `def` without a decorator.
    let decl = LirDecl::Function {
        name: "helper".into(),
        params: vec![],
        return_type: None,
        body: null_lit(),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "# Generated by Dwarf\n\ndef helper():\n    return None"
    );
}

#[test]
fn test_py_function_with_params() {
    let decl = LirDecl::Function {
        name: "add".into(),
        params: vec![
            param("a", Some(Type::Named("Int".into()))),
            param("b", Some(Type::Named("Int".into()))),
        ],
        return_type: Some(Type::Named("Int".into())),
        body: LirExpr::Binary {
            op: LirBinaryOp::Add,
            lhs: Box::new(var("a")),
            rhs: Box::new(var("b")),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "# Generated by Dwarf\n\ndef add(a: int, b: int) -> int:\n    return a + b"
    );
}

#[test]
fn test_py_function_with_return_type() {
    let decl = LirDecl::Function {
        name: "greet".into(),
        params: vec![param("name", Some(Type::Named("String".into())))],
        return_type: Some(Type::Named("String".into())),
        body: var("name"),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "# Generated by Dwarf\n\ndef greet(name: str) -> str:\n    return name"
    );
}

// ==================================================================
// Section 2: Type declarations via emit_decl
// ==================================================================

#[test]
fn test_py_record_def() {
    let decl = LirDecl::RecordDef {
        name: "Point".into(),
        fields: vec![
            LirField {
                name: "x".into(),
                type_: Type::Named("Int".into()),
            },
            LirField {
                name: "y".into(),
                type_: Type::Named("Int".into()),
            },
        ],
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "# Generated by Dwarf\n\nfrom dataclasses import dataclass\n\n\n@dataclass\nclass Point:\n    x: int\n    y: int"
    );
}

#[test]
fn test_py_union_def() {
    let decl = LirDecl::UnionDef {
        name: "Option".into(),
        variants: vec![
            LirVariant {
                name: "Some".into(),
                arg: Some(Type::Named("Int".into())),
            },
            LirVariant {
                name: "None".into(),
                arg: None,
            },
        ],
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "# Generated by Dwarf\n\nfrom typing import Union\n\n\nOption = Union[int, None]"
    );
}

// ==================================================================
// Section 3: Expression emission
// ==================================================================

#[test]
fn test_py_literal_int() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: int_lit(42),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("return 42"));
}

#[test]
fn test_py_literal_float() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: float_lit(3.5),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("return 3.5"));
}

#[test]
fn test_py_literal_str() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: str_lit("hello"),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("return \"hello\"") || result.contains("return 'hello'"));
}

#[test]
fn test_py_literal_bool() {
    let decl_true = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: bool_lit(true),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result_true = emit_program(vec![decl_true]);
    assert!(result_true.contains("return True"));

    let decl_false = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: bool_lit(false),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result_false = emit_program(vec![decl_false]);
    assert!(result_false.contains("return False"));
}

#[test]
fn test_py_literal_null() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: null_lit(),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("return None"));
}

#[test]
fn test_py_variable() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![param("x", Some(Type::Named("Int".into())))],
        return_type: None,
        body: var("x"),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("return x"));
}

// ==================================================================
// Section 3b: Binary and unary operators
// ==================================================================

#[test]
fn test_py_binary_arithmetic() {
    let decl = LirDecl::Function {
        name: "calc".into(),
        params: vec![
            param("a", Some(Type::Named("Int".into()))),
            param("b", Some(Type::Named("Int".into()))),
        ],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Add,
            lhs: Box::new(var("a")),
            rhs: Box::new(var("b")),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "# Generated by Dwarf\n\ndef calc(a: int, b: int):\n    return a + b"
    );
}

#[test]
fn test_py_binary_sub() {
    let decl = LirDecl::Function {
        name: "sub".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Sub,
            lhs: Box::new(int_lit(10)),
            rhs: Box::new(int_lit(3)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("10 - 3"));
}

#[test]
fn test_py_binary_mul() {
    let decl = LirDecl::Function {
        name: "mul".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Mul,
            lhs: Box::new(int_lit(6)),
            rhs: Box::new(int_lit(7)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("6 * 7"));
}

#[test]
fn test_py_binary_div() {
    let decl = LirDecl::Function {
        name: "div".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Div,
            lhs: Box::new(int_lit(10)),
            rhs: Box::new(int_lit(2)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("10 // 2") || result.contains("10 / 2"));
}

#[test]
fn test_py_binary_eq() {
    let decl = LirDecl::Function {
        name: "eq".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Eq,
            lhs: Box::new(int_lit(1)),
            rhs: Box::new(int_lit(2)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("1 == 2"));
}

#[test]
fn test_py_binary_ne() {
    let decl = LirDecl::Function {
        name: "ne".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Ne,
            lhs: Box::new(int_lit(1)),
            rhs: Box::new(int_lit(2)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("1 != 2"));
}

#[test]
fn test_py_binary_lt_gt() {
    let decl = LirDecl::Function {
        name: "cmp".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Lt,
            lhs: Box::new(int_lit(1)),
            rhs: Box::new(int_lit(2)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("1 < 2"));

    let decl_gt = LirDecl::Function {
        name: "cmp_gt".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Gt,
            lhs: Box::new(int_lit(3)),
            rhs: Box::new(int_lit(2)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result_gt = emit_program(vec![decl_gt]);
    assert!(result_gt.contains("3 > 2"));
}

#[test]
fn test_py_binary_le_ge() {
    let decl = LirDecl::Function {
        name: "cmp_le".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Le,
            lhs: Box::new(int_lit(1)),
            rhs: Box::new(int_lit(1)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("1 <= 1"));
}

#[test]
fn test_py_binary_and_or() {
    let decl = LirDecl::Function {
        name: "logic".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::And,
            lhs: Box::new(bool_lit(true)),
            rhs: Box::new(bool_lit(false)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("and"), "Python uses `and` not `&&`");

    let decl_or = LirDecl::Function {
        name: "logic_or".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Binary {
            op: LirBinaryOp::Or,
            lhs: Box::new(bool_lit(true)),
            rhs: Box::new(bool_lit(false)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result_or = emit_program(vec![decl_or]);
    assert!(result_or.contains("or"), "Python uses `or` not `||`");
}

#[test]
fn test_py_unary_neg() {
    let decl = LirDecl::Function {
        name: "negate".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Unary {
            op: LirUnaryOp::Neg,
            expr: Box::new(int_lit(5)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("-5"));
}

#[test]
fn test_py_unary_not() {
    let decl = LirDecl::Function {
        name: "invert".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Unary {
            op: LirUnaryOp::Not,
            expr: Box::new(bool_lit(true)),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("not"), "Python uses `not` not `!`");
}

// ==================================================================
// Section 3c: Control flow expressions
// ==================================================================

#[test]
fn test_py_if_else_ternary() {
    let decl = LirDecl::Function {
        name: "max".into(),
        params: vec![
            param("a", Some(Type::Named("Int".into()))),
            param("b", Some(Type::Named("Int".into()))),
        ],
        return_type: None,
        body: LirExpr::If {
            cond: Box::new(LirExpr::Binary {
                op: LirBinaryOp::Gt,
                lhs: Box::new(var("a")),
                rhs: Box::new(var("b")),
                hint: no_hint(),
                span: s(),
            }),
            then: Box::new(var("a")),
            else_: Some(Box::new(var("b"))),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    // Python ternary: a if cond else b
    assert!(result.contains("if") && result.contains("else"));
}

#[test]
fn test_py_call_function() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Call {
            func: Box::new(var("add")),
            args: vec![int_lit(1), int_lit(2)],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "# Generated by Dwarf\n\ndef main():\n    return add(1, 2)"
    );
}

#[test]
fn test_py_lambda() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Lambda {
            params: vec![LirParam {
                name: "x".into(),
                type_: None,
            }],
            body: Box::new(LirExpr::Binary {
                op: LirBinaryOp::Add,
                lhs: Box::new(var("x")),
                rhs: Box::new(int_lit(1)),
                hint: no_hint(),
                span: s(),
            }),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("lambda"),
        "Python lambdas use the `lambda` keyword"
    );
    assert!(result.contains("x"), "lambda should reference parameter");
}

#[test]
fn test_py_record_expr() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Record {
            fields: vec![("x".into(), int_lit(1)), ("y".into(), int_lit(2))],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("{\"x\"") || result.contains("{'x'"),
        "record should emit dict literal with string keys"
    );
    assert!(
        result.contains("1") && result.contains("2"),
        "dict literal should contain field values"
    );
}

#[test]
fn test_py_array_expr() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Array {
            items: vec![int_lit(1), int_lit(2), int_lit(3)],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("[1, 2, 3]") || result.contains("[1,2,3]"),
        "array should emit Python list literal"
    );
}

#[test]
fn test_py_block_with_let() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: Some(Type::Named("Int".into())),
        body: LirExpr::Block {
            stmts: vec![
                LirStmt::Let {
                    pat: LirPat::Variable("x".into()),
                    value: int_lit(1),
                },
                LirStmt::Expr(LirExpr::Binary {
                    op: LirBinaryOp::Add,
                    lhs: Box::new(var("x")),
                    rhs: Box::new(int_lit(1)),
                    hint: no_hint(),
                    span: s(),
                }),
            ],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("x = 1"),
        "block should contain let assignment"
    );
    assert!(
        result.contains("return x + 1") || result.contains("x + 1"),
        "block should contain return expression"
    );
}

// ==================================================================
// Section 4: Pattern emission
// ==================================================================

#[test]
fn test_py_match_ternary() {
    let decl = LirDecl::Function {
        name: "label".into(),
        params: vec![param("x", Some(Type::Named("Int".into())))],
        return_type: None,
        body: LirExpr::Match {
            expr: Box::new(var("x")),
            arms: vec![
                LirArm {
                    pattern: LirPat::Literal(LirLiteral::Int(1)),
                    guard: None,
                    body: str_lit("one"),
                },
                LirArm {
                    pattern: LirPat::Wildcard,
                    guard: None,
                    body: str_lit("other"),
                },
            ],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    // Python match/case (3.10+) or if/else chain
    assert!(
        result.contains("match") || (result.contains("if") && result.contains("else")),
        "match should emit pattern matching or ternary chain"
    );
}

#[test]
fn test_py_pattern_wildcard() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Match {
            expr: Box::new(int_lit(0)),
            arms: vec![LirArm {
                pattern: LirPat::Wildcard,
                guard: None,
                body: null_lit(),
            }],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.contains("_"), "wildcard pattern should emit `_`");
}

#[test]
fn test_py_pattern_variable() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Match {
            expr: Box::new(int_lit(0)),
            arms: vec![LirArm {
                pattern: LirPat::Variable("val".into()),
                guard: None,
                body: var("val"),
            }],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("val"),
        "variable pattern should emit the binding name"
    );
}

// ==================================================================
// Section 5: Target hint / effect mapping
// ==================================================================

#[test]
fn test_py_async_function() {
    let decl = LirDecl::Function {
        name: "fetchData".into(),
        params: vec![param("url", Some(Type::Named("String".into())))],
        return_type: None,
        body: null_lit(),
        effect: Effect::Async,
        hint: TargetHint::Async,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    // Python uses `async def` for async functions
    assert!(
        result.contains("async def"),
        "async function should use `async def`"
    );
    // Function name should be snake_case
    assert!(
        result.contains("fetch_data") || result.contains("fetchData"),
        "function name should be present"
    );
}

// ==================================================================
// Section 6: Module-level emission
// ==================================================================

#[test]
fn test_py_module_header() {
    let decl = LirDecl::Function {
        name: "noop".into(),
        params: vec![],
        return_type: None,
        body: null_lit(),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    let first_line = result.lines().next().unwrap_or("");
    assert!(
        first_line.starts_with("# Generated by Dwarf"),
        "output should start with Python comment header, got: {first_line:?}"
    );
}

#[test]
fn test_py_mixed_module() {
    let record_decl = LirDecl::RecordDef {
        name: "Point".into(),
        fields: vec![
            LirField {
                name: "x".into(),
                type_: Type::Named("Int".into()),
            },
            LirField {
                name: "y".into(),
                type_: Type::Named("Int".into()),
            },
        ],
        is_pub: true,
        span: s(),
    };
    let func_decl = LirDecl::Function {
        name: "getOrigin".into(),
        params: vec![],
        return_type: None,
        body: null_lit(),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let union_decl = LirDecl::UnionDef {
        name: "Option".into(),
        variants: vec![
            LirVariant {
                name: "Some".into(),
                arg: Some(Type::Named("Int".into())),
            },
            LirVariant {
                name: "None".into(),
                arg: None,
            },
        ],
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![record_decl, func_decl, union_decl]);
    // Verify header
    assert!(result.starts_with("# Generated by Dwarf"));
    // Verify all three declarations appear in order
    assert!(result.contains("class Point"), "should contain Point class");
    assert!(
        result.contains("def getOrigin") || result.contains("def get_origin"),
        "should contain function def"
    );
    assert!(
        result.contains("Option") || result.contains("Union"),
        "should contain union type alias"
    );
}

// ==================================================================
// Section 7: Complex expression combinations
// ==================================================================

#[test]
fn test_py_member_call() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Call {
            func: Box::new(LirExpr::Member {
                obj: Box::new(var("obj")),
                field: "method".into(),
                hint: no_hint(),
                span: s(),
            }),
            args: vec![int_lit(42)],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("obj.method"),
        "member access should use dot notation"
    );
    assert!(result.contains("42"), "method call should pass arguments");
}

#[test]
fn test_py_lambda_call() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Call {
            func: Box::new(LirExpr::Member {
                obj: Box::new(var("items")),
                field: "map".into(),
                hint: no_hint(),
                span: s(),
            }),
            args: vec![LirExpr::Lambda {
                params: vec![LirParam {
                    name: "x".into(),
                    type_: None,
                }],
                body: Box::new(LirExpr::Binary {
                    op: LirBinaryOp::Add,
                    lhs: Box::new(var("x")),
                    rhs: Box::new(int_lit(1)),
                    hint: no_hint(),
                    span: s(),
                }),
                hint: no_hint(),
                span: s(),
            }],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("lambda x"),
        "lambda expression should reference parameter"
    );
    assert!(
        result.contains("items.map") || result.contains("map("),
        "method call on items"
    );
}

// ==================================================================
// Section 8: Edge cases
// ==================================================================

#[test]
fn test_py_function_no_params() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: null_lit(),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(
        result.contains("def main():"),
        "function with no params should have empty parens"
    );
}

#[test]
fn test_py_no_trailing_whitespace() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: int_lit(42),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    // Last char should not be whitespace
    assert!(
        !result.ends_with(' ') && !result.ends_with('\n'),
        "output should not have trailing whitespace"
    );
}

#[test]
fn test_py_empty_module_strict() {
    let mut backend = PythonBackend::new();
    let result = backend.emit_module(&[]).unwrap();
    assert_eq!(result, "", "empty module must produce empty string");
}
