//! End-to-end integration tests for the TypeScript backend.
//!
//! Each test constructs a complete LIR program (one or more declarations),
//! emits it through [`TypeScriptBackend`], and verifies the TypeScript
//! output matches the expected form.

use dwarf_emitter::backend::EmitterBackend;
use dwarf_emitter::ts::backend::TypeScriptBackend;
use dwarf_lir::{
    Effect, LirArm, LirBinaryOp, LirDecl, LirExpr, LirField, LirLiteral, LirParam, LirPat, LirStmt,
    LirVariant, TargetHint,
};
use dwarf_syntax::hir::Type;
use dwarf_syntax::span::Span;

// ------------------------------------------------------------------
// Helpers
// ------------------------------------------------------------------

fn s() -> Span {
    Span::new(0, 0, 0)
}

fn no_hint() -> TargetHint {
    TargetHint::None
}

fn int_lit(v: i64) -> LirExpr {
    LirExpr::Literal {
        value: LirLiteral::Int(v),
        hint: no_hint(),
        span: s(),
    }
}

fn str_lit(v: &str) -> LirExpr {
    LirExpr::Literal {
        value: LirLiteral::Str(v.to_string()),
        hint: no_hint(),
        span: s(),
    }
}

fn null_lit() -> LirExpr {
    LirExpr::Literal {
        value: LirLiteral::Null,
        hint: no_hint(),
        span: s(),
    }
}

fn var(name: &str) -> LirExpr {
    LirExpr::Variable {
        name: name.to_string(),
        hint: no_hint(),
        span: s(),
    }
}

fn param(name: &str, type_: Option<Type>) -> LirParam {
    LirParam {
        name: name.to_string(),
        type_,
    }
}

fn emit_program(decls: Vec<LirDecl>) -> String {
    let mut backend = TypeScriptBackend::new("0.1.0");
    backend.emit_module(&decls).unwrap()
}

// ==================================================================
// Test 1: simple_function
// ==================================================================

#[test]
fn test_e2e_simple_function() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: int_lit(42),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport function main() { return 42; }"
    );
}

// ==================================================================
// Test 2: function_with_params
// ==================================================================

#[test]
fn test_e2e_function_with_params() {
    let decl = LirDecl::Function {
        name: "add".into(),
        params: vec![
            param("a", Some(Type::Named("Int".into()))),
            param("b", Some(Type::Named("Int".into()))),
        ],
        return_type: Some(Type::Named("Int".into())),
        body: LirExpr::Binary {
            op: LirBinaryOp::Add,
            lhs: Box::new(var("a")),
            rhs: Box::new(var("b")),
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport function add(a: number, b: number): number { return a + b; }"
    );
}

// ==================================================================
// Test 3: record_interface
// ==================================================================

#[test]
fn test_e2e_record_interface() {
    let decl = LirDecl::RecordDef {
        name: "Point".into(),
        fields: vec![
            LirField {
                name: "x".into(),
                type_: Type::Named("Int".into()),
            },
            LirField {
                name: "y".into(),
                type_: Type::Named("Int".into()),
            },
        ],
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport interface Point { x: number; y: number; }"
    );
}

// ==================================================================
// Test 4: union_type
// ==================================================================

#[test]
fn test_e2e_union_type() {
    let decl = LirDecl::UnionDef {
        name: "Option".into(),
        variants: vec![
            LirVariant {
                name: "Some".into(),
                arg: Some(Type::Named("Int".into())),
            },
            LirVariant {
                name: "None".into(),
                arg: None,
            },
        ],
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport type Option = Some | None;"
    );
}

// ==================================================================
// Test 5: match_ternary — match in body → ternary chain
// ==================================================================

#[test]
fn test_e2e_match_ternary() {
    let decl = LirDecl::Function {
        name: "label".into(),
        params: vec![param("x", Some(Type::Named("Int".into())))],
        return_type: Some(Type::Named("String".into())),
        body: LirExpr::Match {
            expr: Box::new(var("x")),
            arms: vec![
                LirArm {
                    pattern: LirPat::Literal(LirLiteral::Int(1)),
                    guard: None,
                    body: str_lit("one"),
                },
                LirArm {
                    pattern: LirPat::Wildcard,
                    guard: None,
                    body: str_lit("other"),
                },
            ],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport function label(x: number): string { return x === 1 ? \"one\" : \"other\"; }"
    );
}

// ==================================================================
// Test 6: react_component — const Btn: React.FC<BtnProps>
// ==================================================================

#[test]
fn test_e2e_react_component() {
    let decl = LirDecl::Function {
        name: "Btn".into(),
        params: vec![],
        return_type: None,
        body: str_lit("Click me"),
        effect: Effect::Pure,
        hint: TargetHint::ReactComponent,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport const Btn: React.FC<BtnProps> = () => {\n  return (\"Click me\");\n};"
    );
}

// ==================================================================
// Test 7: mixed_module — function + interface + type alias
// ==================================================================

#[test]
fn test_e2e_mixed_module() {
    let record_decl = LirDecl::RecordDef {
        name: "Point".into(),
        fields: vec![
            LirField {
                name: "x".into(),
                type_: Type::Named("Int".into()),
            },
            LirField {
                name: "y".into(),
                type_: Type::Named("Int".into()),
            },
        ],
        is_pub: true,
        span: s(),
    };
    let func_decl = LirDecl::Function {
        name: "getOrigin".into(),
        params: vec![],
        return_type: None,
        body: null_lit(),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let union_decl = LirDecl::UnionDef {
        name: "Option".into(),
        variants: vec![
            LirVariant {
                name: "Some".into(),
                arg: Some(Type::Named("Int".into())),
            },
            LirVariant {
                name: "None".into(),
                arg: None,
            },
        ],
        is_pub: true,
        span: s(),
    };
    let result = emit_program(vec![record_decl, func_decl, union_decl]);
    // Verify all three declarations appear in order
    assert!(result.starts_with("// Generated by Dwarf v0.1.0 -- edit source, not this file"));
    assert!(result.contains("export interface Point"));
    assert!(result.contains("export function getOrigin"));
    assert!(result.contains("export type Option"));
    // Verify Interface appears before function (order preserved)
    let pos_point = result.find("interface Point").unwrap();
    let pos_get_origin = result.find("function getOrigin").unwrap();
    let pos_option = result.find("type Option").unwrap();
    assert!(
        pos_point < pos_get_origin,
        "record should come before function"
    );
    assert!(
        pos_get_origin < pos_option,
        "function should come before union"
    );
}

// ==================================================================
// Test 8: async_function
// ==================================================================

#[test]
fn test_e2e_async_function() {
    let decl = LirDecl::Function {
        name: "fetchData".into(),
        params: vec![param("url", Some(Type::Named("String".into())))],
        return_type: Some(Type::Generic {
            base: "Promise".into(),
            args: vec![Type::Named("String".into())],
        }),
        body: null_lit(),
        effect: Effect::Async,
        hint: TargetHint::Async,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert!(result.starts_with("// Generated by Dwarf v0.1.0 -- edit source, not this file"));
    assert!(result.contains("export async function fetchData"));
    assert!(result.contains("url: string"));
    assert!(result.contains("Promise<string>"));
    assert!(result.contains("return null;"));
}

// ==================================================================
// Test 9: call_other_func — calls another function
// ==================================================================

#[test]
fn test_e2e_call_other_func() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Call {
            func: Box::new(var("add")),
            args: vec![int_lit(1), int_lit(2)],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport function main() { return add(1, 2); }"
    );
}

// ==================================================================
// Test 10: block_stmts — block with let and return
// ==================================================================

#[test]
fn test_e2e_block_stmts() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: Some(Type::Named("Int".into())),
        body: LirExpr::Block {
            stmts: vec![
                LirStmt::Let {
                    pat: LirPat::Variable("x".into()),
                    value: int_lit(1),
                },
                LirStmt::Expr(LirExpr::Binary {
                    op: LirBinaryOp::Add,
                    lhs: Box::new(var("x")),
                    rhs: Box::new(int_lit(1)),
                    hint: no_hint(),
                    span: s(),
                }),
            ],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport function main(): number {\n  let x = 1;\n  return x + 1;\n}"
    );
}

// ==================================================================
// Test 11: complex_expr — obj.method(a + b * c)
// ==================================================================

#[test]
fn test_e2e_complex_expr() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Call {
            func: Box::new(LirExpr::Member {
                obj: Box::new(var("obj")),
                field: "method".into(),
                hint: no_hint(),
                span: s(),
            }),
            args: vec![LirExpr::Binary {
                op: LirBinaryOp::Add,
                lhs: Box::new(var("a")),
                rhs: Box::new(LirExpr::Binary {
                    op: LirBinaryOp::Mul,
                    lhs: Box::new(var("b")),
                    rhs: Box::new(var("c")),
                    hint: no_hint(),
                    span: s(),
                }),
                hint: no_hint(),
                span: s(),
            }],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport function main() { return obj.method(a + b * c); }"
    );
}

// ==================================================================
// Test 12: array_records — [{ x: 1 }, { x: 2 }]
// ==================================================================

#[test]
fn test_e2e_array_records() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Array {
            items: vec![
                LirExpr::Record {
                    fields: vec![("x".into(), int_lit(1))],
                    hint: no_hint(),
                    span: s(),
                },
                LirExpr::Record {
                    fields: vec![("x".into(), int_lit(2))],
                    hint: no_hint(),
                    span: s(),
                },
            ],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport function main() { return [{ x: 1 }, { x: 2 }]; }"
    );
}

// ==================================================================
// Test 13: lambda_call — items.map((x) => x + 1)
// ==================================================================

#[test]
fn test_e2e_lambda_call() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Call {
            func: Box::new(LirExpr::Member {
                obj: Box::new(var("items")),
                field: "map".into(),
                hint: no_hint(),
                span: s(),
            }),
            args: vec![LirExpr::Lambda {
                params: vec![LirParam {
                    name: "x".into(),
                    type_: None,
                }],
                body: Box::new(LirExpr::Binary {
                    op: LirBinaryOp::Add,
                    lhs: Box::new(var("x")),
                    rhs: Box::new(int_lit(1)),
                    hint: no_hint(),
                    span: s(),
                }),
                hint: no_hint(),
                span: s(),
            }],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport function main() { return items.map((x) => x + 1); }"
    );
}

// ==================================================================
// Test 14: assert_eq — expect(42).toBe(42)
// ==================================================================

#[test]
fn test_e2e_assert_eq() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Call {
            func: Box::new(var("assert_eq")),
            args: vec![int_lit(42), int_lit(42)],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport function main() { return expect(42).toBe(42); }"
    );
}

// ==================================================================
// Test 15: header_present — Generated by Dwarf header
// ==================================================================

#[test]
fn test_e2e_header_present() {
    let decl = LirDecl::Function {
        name: "noop".into(),
        params: vec![],
        return_type: None,
        body: null_lit(),
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: false,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    let first_line = result.lines().next().unwrap_or("");
    assert!(
        first_line.starts_with("// Generated by Dwarf"),
        "output should start with generated header, got: {first_line:?}"
    );
    assert!(
        first_line.contains("v0.1.0"),
        "header should contain version string, got: {first_line:?}"
    );
}

// ==================================================================
// Test 16: assert.equal(a,b) → expect(a).toBe(b)  [RED PHASE]
// ==================================================================
//
// The emitter currently only matches flat Variable func names
// ("assert"/"assert_eq"), so assert.equal (which uses a Member
// expression for the func) falls through to regular call emission.
// This test asserts the *desired* output and will fail until the
// emitter is extended.

#[test]
fn test_assert_equal_emits_expect_to_be() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Call {
            func: Box::new(LirExpr::Member {
                obj: Box::new(LirExpr::Variable {
                    name: "assert".into(),
                    hint: no_hint(),
                    span: s(),
                }),
                field: "equal".into(),
                hint: no_hint(),
                span: s(),
            }),
            args: vec![var("a"), var("b")],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport function main() { return expect(a).toBe(b); }"
    );
}

// ==================================================================
// Test 17: assert.ok(val) → expect(val).toBeTruthy()  [RED PHASE]
// ==================================================================

#[test]
fn test_assert_ok_emits_expect_to_be_truthy() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Call {
            func: Box::new(LirExpr::Member {
                obj: Box::new(LirExpr::Variable {
                    name: "assert".into(),
                    hint: no_hint(),
                    span: s(),
                }),
                field: "ok".into(),
                hint: no_hint(),
                span: s(),
            }),
            args: vec![var("value")],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport function main() { return expect(value).toBeTruthy(); }"
    );
}

// ==================================================================
// Test 18: assert.error(fn) → expect(fn).toThrow()  [RED PHASE]
// ==================================================================

#[test]
fn test_assert_error_emits_expect_to_throw() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Call {
            func: Box::new(LirExpr::Member {
                obj: Box::new(LirExpr::Variable {
                    name: "assert".into(),
                    hint: no_hint(),
                    span: s(),
                }),
                field: "error".into(),
                hint: no_hint(),
                span: s(),
            }),
            args: vec![var("fn")],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport function main() { return expect(fn).toThrow(); }"
    );
}

// ==================================================================
// Test 19: assert.struct(a,b) → expect(a).toEqual(b)  [RED PHASE]
// ==================================================================

#[test]
fn test_assert_struct_emits_expect_to_equal() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Call {
            func: Box::new(LirExpr::Member {
                obj: Box::new(LirExpr::Variable {
                    name: "assert".into(),
                    hint: no_hint(),
                    span: s(),
                }),
                field: "struct".into(),
                hint: no_hint(),
                span: s(),
            }),
            args: vec![var("a"), var("b")],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport function main() { return expect(a).toEqual(b); }"
    );
}

// ==================================================================
// Test 20: assert(val) still compiles  [GREEN PHASE guard]
// ==================================================================
//
// Verifies the existing `assert(value)` → `expect(value).toBe(true)`
// path still works and wasn't broken by changes.

#[test]
fn test_assert_val_still_works() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Call {
            func: Box::new(var("assert")),
            args: vec![var("x")],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport function main() { return expect(x).toBe(true); }"
    );
}

// ==================================================================
// Test 21: assert_eq(a,b) still compiles  [GREEN PHASE guard]
// ==================================================================
//
// Verifies the existing `assert_eq(a,b)` → `expect(a).toBe(b)`
// path still works and wasn't broken by changes.

#[test]
fn test_assert_eq_still_works() {
    let decl = LirDecl::Function {
        name: "main".into(),
        params: vec![],
        return_type: None,
        body: LirExpr::Call {
            func: Box::new(var("assert_eq")),
            args: vec![var("a"), var("b")],
            hint: no_hint(),
            span: s(),
        },
        effect: Effect::Pure,
        hint: TargetHint::None,
        is_pub: true,
        is_generator: false,
        span: s(),
    };
    let result = emit_program(vec![decl]);
    assert_eq!(
        result,
        "// Generated by Dwarf v0.1.0 -- edit source, not this file\n\nexport function main() { return expect(a).toBe(b); }"
    );
}
