/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Compile Dwarf source code and return the result as a JSON string.
 *
 * JS usage:
 * ```js
 * const result = JSON.parse(compile(source, filename, JSON.stringify({ target: "ts" })));
 * ```
 */
export declare function compile(source: string, filename: string, optionsJson: string): string

/** Simplified compile with default options (TypeScript target). */
export declare function compileSimple(source: string, filename: string): string

/** Get the compiler version. */
export declare function version(): string
